package config

import (
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLoad_ValidDefaultConfig(t *testing.T) {
	// No env vars set — should load with defaults and auto-generate JWT secret.
	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, "127.0.0.1", cfg.Host)
	assert.Equal(t, 13120, cfg.Port)
	// Auto-generated JWT secret must be 64 hex chars (32 bytes).
	assert.Len(t, cfg.JWTSecret, 64)
}

func TestLoad_DefaultsAppliedWhenEnvAbsent(t *testing.T) {
	defaults := Defaults()
	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, defaults.Host, cfg.Host)
	assert.Equal(t, defaults.Port, cfg.Port)
}

func TestLoad_CustomValuesFromEnv(t *testing.T) {
	t.Setenv("DASHBOARD_HOST", "localhost")
	t.Setenv("DASHBOARD_PORT", "9090")

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, "localhost", cfg.Host)
	assert.Equal(t, 9090, cfg.Port)
}

// A moved operational key set in the environment is ignored: Load still
// succeeds and the field no longer exists on Config.
func TestLoad_MovedKeyInEnvIsIgnoredAndWarned(t *testing.T) {
	t.Setenv("DASHBOARD_SPAWN_RATE_LIMIT", "999")

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, "127.0.0.1", cfg.Host)
}

func TestLoad_JWTSecretTooShort(t *testing.T) {
	t.Setenv("DASHBOARD_JWT_SECRET", "tooshort")

	_, err := Load("")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "DASHBOARD_JWT_SECRET must be at least 32 characters")
}

func TestLoad_JWTSecretExactly32Chars(t *testing.T) {
	secret := "abcdefghijklmnopqrstuvwxyz123456" // exactly 32 chars
	t.Setenv("DASHBOARD_JWT_SECRET", secret)

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, secret, cfg.JWTSecret)
}

func TestLoad_JWTSecretLongerThan32Chars(t *testing.T) {
	secret := "abcdefghijklmnopqrstuvwxyz1234567890abcdef" // > 32 chars
	t.Setenv("DASHBOARD_JWT_SECRET", secret)

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, secret, cfg.JWTSecret)
}

func TestLoad_IsLoopback(t *testing.T) {
	cfg, err := Load("")
	require.NoError(t, err)
	assert.True(t, cfg.IsLoopback())
}

func TestLoad_Addr(t *testing.T) {
	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, "127.0.0.1:13120", cfg.Addr())
}

// -------------------------------------------------------------------
// F-SEC-003: non-loopback bind must fail-closed unless opted-in
// -------------------------------------------------------------------

func TestLoad_NonLoopbackHost_RefusesBootWithoutOptIn(t *testing.T) {
	t.Setenv("DASHBOARD_HOST", "0.0.0.0")
	os.Unsetenv("DASHBOARD_REMOTES_ENABLED") //nolint:errcheck

	_, err := Load("")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "DASHBOARD_HOST=")
	assert.Contains(t, err.Error(), "DASHBOARD_REMOTES_ENABLED=true")
}

func TestLoad_NonLoopbackHost_AllowsBootWhenOptedIn(t *testing.T) {
	t.Setenv("DASHBOARD_HOST", "0.0.0.0")
	t.Setenv("DASHBOARD_REMOTES_ENABLED", "true")

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, "0.0.0.0", cfg.Host)
}

func TestLoad_LocalhostHost_DoesNotRequireOptIn(t *testing.T) {
	t.Setenv("DASHBOARD_HOST", "localhost")
	os.Unsetenv("DASHBOARD_REMOTES_ENABLED") //nolint:errcheck

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, "localhost", cfg.Host)
}

func TestLoad_Ipv6Loopback_DoesNotRequireOptIn(t *testing.T) {
	t.Setenv("DASHBOARD_HOST", "::1")
	os.Unsetenv("DASHBOARD_REMOTES_ENABLED") //nolint:errcheck

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, "::1", cfg.Host)
}

// -------------------------------------------------------------------
// F-SEC-008: hooks secret auto-generation
// -------------------------------------------------------------------

func TestLoad_HooksSecretAutoGenerated_WhenEnvUnset(t *testing.T) {
	os.Unsetenv("DASHBOARD_HOOKS_SECRET") //nolint:errcheck

	cfg, err := Load("")
	require.NoError(t, err)
	assert.NotEmpty(t, cfg.HooksSecret, "HooksSecret must be auto-generated when env is unset")
	assert.GreaterOrEqual(t, len(cfg.HooksSecret), 32, "auto-generated secret must be at least 32 chars")
}

func TestLoad_HooksSecretFromEnv_UsedAsIs(t *testing.T) {
	const secret = "my-hooks-secret-that-is-long-enough-to-pass"
	t.Setenv("DASHBOARD_HOOKS_SECRET", secret)

	cfg, err := Load("")
	require.NoError(t, err)
	assert.Equal(t, secret, cfg.HooksSecret)
}
