// Code generated by ent, DO NOT EDIT.

package permissionpreset

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the permissionpreset type in the database.
	Label = "permission_preset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProjectCwd holds the string denoting the project_cwd field in the database.
	FieldProjectCwd = "project_cwd"
	// FieldTool holds the string denoting the tool field in the database.
	FieldTool = "tool"
	// FieldPattern holds the string denoting the pattern field in the database.
	FieldPattern = "pattern"
	// Table holds the table name of the permissionpreset in the database.
	Table = "permission_presets"
)

// Columns holds all SQL columns for permissionpreset fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProjectCwd,
	FieldTool,
	FieldPattern,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PermissionPreset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProjectCwd orders the results by the project_cwd field.
func ByProjectCwd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectCwd, opts...).ToFunc()
}

// ByTool orders the results by the tool field.
func ByTool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTool, opts...).ToFunc()
}

// ByPattern orders the results by the pattern field.
func ByPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPattern, opts...).ToFunc()
}
