// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "key_hash", Type: field.TypeString, Unique: true},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_key_hash",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[2]},
			},
			{
				Name:    "apikey_active",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
		},
	}
	// PipelineConfigsColumns holds the columns for the "pipeline_configs" table.
	PipelineConfigsColumns = []*schema.Column{
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
	}
	// PipelineConfigsTable holds the schema information for the "pipeline_configs" table.
	PipelineConfigsTable = &schema.Table{
		Name:       "pipeline_configs",
		Columns:    PipelineConfigsColumns,
		PrimaryKey: []*schema.Column{PipelineConfigsColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "cwd", Type: field.TypeString},
		{Name: "current_stage", Type: field.TypeString, Default: "concept"},
		{Name: "priority", Type: field.TypeString, Default: "medium"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "github_login", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		PipelineConfigsTable,
		TasksTable,
		UsersTable,
	}
)

func init() {
}
