// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgentCostTrendsColumns holds the columns for the "agent_cost_trends" table.
	AgentCostTrendsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "input_tokens", Type: field.TypeInt},
		{Name: "output_tokens", Type: field.TypeInt},
		{Name: "cost_usd", Type: field.TypeFloat64},
		{Name: "recorded_at", Type: field.TypeTime},
		{Name: "cwd", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "project_path", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "project_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "source_mtime", Type: field.TypeInt64, Nullable: true, Default: 0},
	}
	// AgentCostTrendsTable holds the schema information for the "agent_cost_trends" table.
	AgentCostTrendsTable = &schema.Table{
		Name:       "agent_cost_trends",
		Columns:    AgentCostTrendsColumns,
		PrimaryKey: []*schema.Column{AgentCostTrendsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "agentcosttrend_session_id",
				Unique:  true,
				Columns: []*schema.Column{AgentCostTrendsColumns[1]},
			},
			{
				Name:    "agentcosttrend_recorded_at",
				Unique:  false,
				Columns: []*schema.Column{AgentCostTrendsColumns[6]},
			},
			{
				Name:    "agentcosttrend_project_path",
				Unique:  false,
				Columns: []*schema.Column{AgentCostTrendsColumns[8]},
			},
		},
	}
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "key_hash", Type: field.TypeString, Unique: true},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_active",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
		},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "ts", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "action", Type: field.TypeString},
		{Name: "target", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "task_id", Type: field.TypeString, Nullable: true},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_ts",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[1]},
			},
			{
				Name:    "auditevent_user_id_action",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[2], AuditEventsColumns[3]},
			},
			{
				Name:    "auditevent_task_id",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[6]},
			},
		},
	}
	// DriftAlertsColumns holds the columns for the "drift_alerts" table.
	DriftAlertsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "spawner_id", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "stage", Type: field.TypeString},
		{Name: "metric_key", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "open"},
		{Name: "direction", Type: field.TypeString},
		{Name: "baseline_value", Type: field.TypeFloat64},
		{Name: "recent_value", Type: field.TypeFloat64},
		{Name: "delta", Type: field.TypeFloat64},
		{Name: "threshold", Type: field.TypeFloat64},
		{Name: "sample_count", Type: field.TypeInt},
		{Name: "detected_at", Type: field.TypeTime},
		{Name: "acknowledged_at", Type: field.TypeTime, Nullable: true},
	}
	// DriftAlertsTable holds the schema information for the "drift_alerts" table.
	DriftAlertsTable = &schema.Table{
		Name:       "drift_alerts",
		Columns:    DriftAlertsColumns,
		PrimaryKey: []*schema.Column{DriftAlertsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "driftalert_status",
				Unique:  false,
				Columns: []*schema.Column{DriftAlertsColumns[5]},
			},
			{
				Name:    "driftalert_metric_key",
				Unique:  false,
				Columns: []*schema.Column{DriftAlertsColumns[4]},
			},
			{
				Name:    "driftalert_spawner_id_model_stage_metric_key",
				Unique:  true,
				Columns: []*schema.Column{DriftAlertsColumns[1], DriftAlertsColumns[2], DriftAlertsColumns[3], DriftAlertsColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					Where: "status = 'open'",
				},
			},
		},
	}
	// EvalMetricSnapshotsColumns holds the columns for the "eval_metric_snapshots" table.
	EvalMetricSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "spawner_id", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "stage", Type: field.TypeString},
		{Name: "metric_key", Type: field.TypeString},
		{Name: "value", Type: field.TypeFloat64},
		{Name: "sample_count", Type: field.TypeInt},
		{Name: "window_start", Type: field.TypeTime},
		{Name: "window_end", Type: field.TypeTime},
		{Name: "recorded_at", Type: field.TypeTime},
	}
	// EvalMetricSnapshotsTable holds the schema information for the "eval_metric_snapshots" table.
	EvalMetricSnapshotsTable = &schema.Table{
		Name:       "eval_metric_snapshots",
		Columns:    EvalMetricSnapshotsColumns,
		PrimaryKey: []*schema.Column{EvalMetricSnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "evalmetricsnapshot_recorded_at",
				Unique:  false,
				Columns: []*schema.Column{EvalMetricSnapshotsColumns[9]},
			},
			{
				Name:    "evalmetricsnapshot_metric_key",
				Unique:  false,
				Columns: []*schema.Column{EvalMetricSnapshotsColumns[4]},
			},
			{
				Name:    "evalmetricsnapshot_spawner_id_model_stage",
				Unique:  false,
				Columns: []*schema.Column{EvalMetricSnapshotsColumns[1], EvalMetricSnapshotsColumns[2], EvalMetricSnapshotsColumns[3]},
			},
		},
	}
	// PermissionPresetsColumns holds the columns for the "permission_presets" table.
	PermissionPresetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "project_cwd", Type: field.TypeString},
		{Name: "tool", Type: field.TypeString},
		{Name: "pattern", Type: field.TypeString, Nullable: true},
	}
	// PermissionPresetsTable holds the schema information for the "permission_presets" table.
	PermissionPresetsTable = &schema.Table{
		Name:       "permission_presets",
		Columns:    PermissionPresetsColumns,
		PrimaryKey: []*schema.Column{PermissionPresetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permissionpreset_user_id_project_cwd_tool_pattern",
				Unique:  true,
				Columns: []*schema.Column{PermissionPresetsColumns[1], PermissionPresetsColumns[2], PermissionPresetsColumns[3], PermissionPresetsColumns[4]},
			},
		},
	}
	// PermissionRequestsColumns holds the columns for the "permission_requests" table.
	PermissionRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "tool", Type: field.TypeString},
		{Name: "pattern", Type: field.TypeString, Nullable: true},
		{Name: "reason", Type: field.TypeString, Nullable: true},
		{Name: "outcome", Type: field.TypeString, Nullable: true},
		{Name: "requested_at", Type: field.TypeTime},
		{Name: "resolved_at", Type: field.TypeTime, Nullable: true},
		{Name: "stage_run_id", Type: field.TypeString},
	}
	// PermissionRequestsTable holds the schema information for the "permission_requests" table.
	PermissionRequestsTable = &schema.Table{
		Name:       "permission_requests",
		Columns:    PermissionRequestsColumns,
		PrimaryKey: []*schema.Column{PermissionRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "permission_requests_stage_runs_permission_requests",
				Columns:    []*schema.Column{PermissionRequestsColumns[7]},
				RefColumns: []*schema.Column{StageRunsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "permissionrequest_stage_run_id",
				Unique:  false,
				Columns: []*schema.Column{PermissionRequestsColumns[7]},
			},
			{
				Name:    "permissionrequest_outcome",
				Unique:  false,
				Columns: []*schema.Column{PermissionRequestsColumns[4]},
			},
		},
	}
	// PipelineConfigsColumns holds the columns for the "pipeline_configs" table.
	PipelineConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "project_id", Type: field.TypeString, Default: ""},
		{Name: "value", Type: field.TypeString},
	}
	// PipelineConfigsTable holds the schema information for the "pipeline_configs" table.
	PipelineConfigsTable = &schema.Table{
		Name:       "pipeline_configs",
		Columns:    PipelineConfigsColumns,
		PrimaryKey: []*schema.Column{PipelineConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "pipelineconfig_project_id_key",
				Unique:  true,
				Columns: []*schema.Column{PipelineConfigsColumns[2], PipelineConfigsColumns[1]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "default_spawner_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "project_slug",
				Unique:  false,
				Columns: []*schema.Column{ProjectsColumns[1]},
			},
		},
	}
	// ProjectFoldersColumns holds the columns for the "project_folders" table.
	ProjectFoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "path", Type: field.TypeString, Size: 4096},
		{Name: "label", Type: field.TypeString, Nullable: true},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "project_folders", Type: field.TypeString},
	}
	// ProjectFoldersTable holds the schema information for the "project_folders" table.
	ProjectFoldersTable = &schema.Table{
		Name:       "project_folders",
		Columns:    ProjectFoldersColumns,
		PrimaryKey: []*schema.Column{ProjectFoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_folders_projects_folders",
				Columns:    []*schema.Column{ProjectFoldersColumns[5]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectfolder_path_project_folders",
				Unique:  true,
				Columns: []*schema.Column{ProjectFoldersColumns[1], ProjectFoldersColumns[5]},
			},
		},
	}
	// ProviderSettingsColumns holds the columns for the "provider_settings" table.
	ProviderSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "provider_id", Type: field.TypeString, Unique: true},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProviderSettingsTable holds the schema information for the "provider_settings" table.
	ProviderSettingsTable = &schema.Table{
		Name:       "provider_settings",
		Columns:    ProviderSettingsColumns,
		PrimaryKey: []*schema.Column{ProviderSettingsColumns[0]},
	}
	// RefinementTurnsColumns holds the columns for the "refinement_turns" table.
	RefinementTurnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "task_id", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"user", "assistant"}},
		{Name: "content", Type: field.TypeString},
		{Name: "phase", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RefinementTurnsTable holds the schema information for the "refinement_turns" table.
	RefinementTurnsTable = &schema.Table{
		Name:       "refinement_turns",
		Columns:    RefinementTurnsColumns,
		PrimaryKey: []*schema.Column{RefinementTurnsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "refinementturn_task_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RefinementTurnsColumns[1], RefinementTurnsColumns[5]},
			},
		},
	}
	// RemoteRegistrationsColumns holds the columns for the "remote_registrations" table.
	RemoteRegistrationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "bearer_key", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RemoteRegistrationsTable holds the schema information for the "remote_registrations" table.
	RemoteRegistrationsTable = &schema.Table{
		Name:       "remote_registrations",
		Columns:    RemoteRegistrationsColumns,
		PrimaryKey: []*schema.Column{RemoteRegistrationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "remoteregistration_user_id",
				Unique:  false,
				Columns: []*schema.Column{RemoteRegistrationsColumns[1]},
			},
		},
	}
	// SpawnersColumns holds the columns for the "spawners" table.
	SpawnersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "command", Type: field.TypeString},
		{Name: "args", Type: field.TypeJSON},
		{Name: "env", Type: field.TypeJSON},
		{Name: "adapter_type", Type: field.TypeString, Default: "claude"},
		{Name: "adapter_config", Type: field.TypeJSON, Default: "{}"},
		{Name: "model_override", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "built_in", Type: field.TypeBool, Default: false},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SpawnersTable holds the schema information for the "spawners" table.
	SpawnersTable = &schema.Table{
		Name:       "spawners",
		Columns:    SpawnersColumns,
		PrimaryKey: []*schema.Column{SpawnersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "spawner_slug",
				Unique:  false,
				Columns: []*schema.Column{SpawnersColumns[2]},
			},
		},
	}
	// StageRunsColumns holds the columns for the "stage_runs" table.
	StageRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "stage", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString, Nullable: true},
		{Name: "session_name", Type: field.TypeString, Nullable: true},
		{Name: "pid", Type: field.TypeInt, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "iteration", Type: field.TypeInt, Default: 0},
		{Name: "output", Type: field.TypeJSON, Nullable: true},
		{Name: "tokens_used", Type: field.TypeInt, Default: 0},
		{Name: "cost_cents", Type: field.TypeInt, Default: 0},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "ended_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_grant_at", Type: field.TypeTime, Nullable: true},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "next_retry_at", Type: field.TypeTime, Nullable: true},
		{Name: "pending_user_prompt", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: "datetime('now')"},
		{Name: "task_id", Type: field.TypeString},
	}
	// StageRunsTable holds the schema information for the "stage_runs" table.
	StageRunsTable = &schema.Table{
		Name:       "stage_runs",
		Columns:    StageRunsColumns,
		PrimaryKey: []*schema.Column{StageRunsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "stage_runs_tasks_stage_runs",
				Columns:    []*schema.Column{StageRunsColumns[17]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "stagerun_status",
				Unique:  false,
				Columns: []*schema.Column{StageRunsColumns[5]},
			},
			{
				Name:    "stagerun_task_id_stage_iteration",
				Unique:  false,
				Columns: []*schema.Column{StageRunsColumns[17], StageRunsColumns[1], StageRunsColumns[6]},
			},
			{
				Name:    "stagerun_task_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{StageRunsColumns[17], StageRunsColumns[16]},
			},
			{
				Name:    "stagerun_task_id",
				Unique:  true,
				Columns: []*schema.Column{StageRunsColumns[17]},
				Annotation: &entsql.IndexAnnotation{
					Where: "status = 'running'",
				},
			},
		},
	}
	// SystemPromptsColumns holds the columns for the "system_prompts" table.
	SystemPromptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "scope", Type: field.TypeString, Default: "global"},
		{Name: "stage", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemPromptsTable holds the schema information for the "system_prompts" table.
	SystemPromptsTable = &schema.Table{
		Name:       "system_prompts",
		Columns:    SystemPromptsColumns,
		PrimaryKey: []*schema.Column{SystemPromptsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "systemprompt_scope_stage",
				Unique:  false,
				Columns: []*schema.Column{SystemPromptsColumns[1], SystemPromptsColumns[2]},
			},
			{
				Name:    "systemprompt_priority",
				Unique:  false,
				Columns: []*schema.Column{SystemPromptsColumns[4]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "cwd", Type: field.TypeString, Size: 4096},
		{Name: "worktree_path", Type: field.TypeString, Nullable: true},
		{Name: "source_branch", Type: field.TypeString, Nullable: true},
		{Name: "target_branch", Type: field.TypeString, Nullable: true},
		{Name: "current_stage", Type: field.TypeString, Default: "concept"},
		{Name: "priority", Type: field.TypeString, Default: "medium"},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "parent_task_id", Type: field.TypeString, Nullable: true},
		{Name: "max_iterations", Type: field.TypeInt, Default: 20},
		{Name: "token_budget", Type: field.TypeInt, Nullable: true},
		{Name: "cost_budget_cents", Type: field.TypeInt, Nullable: true},
		{Name: "stage_timeout_seconds", Type: field.TypeInt, Default: 1800},
		{Name: "silver_bullet", Type: field.TypeBool, Default: false},
		{Name: "autonomy", Type: field.TypeString, Default: "spec_gated"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeString, Nullable: true},
		{Name: "spawner_id", Type: field.TypeString, Nullable: true},
		{Name: "rank", Type: field.TypeFloat64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "task_current_stage",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[8]},
			},
			{
				Name:    "task_parent_task_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[11]},
			},
			{
				Name:    "task_project_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[19]},
			},
			{
				Name:    "task_silver_bullet_priority_rank_created_at",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[16], TasksColumns[9], TasksColumns[21], TasksColumns[22]},
			},
		},
	}
	// TaskDependenciesColumns holds the columns for the "task_dependencies" table.
	TaskDependenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "required_stage", Type: field.TypeString, Default: "done"},
		{Name: "on_cancel_action", Type: field.TypeString, Default: "on_hold"},
		{Name: "task_id", Type: field.TypeString},
		{Name: "depends_on_id", Type: field.TypeString},
	}
	// TaskDependenciesTable holds the schema information for the "task_dependencies" table.
	TaskDependenciesTable = &schema.Table{
		Name:       "task_dependencies",
		Columns:    TaskDependenciesColumns,
		PrimaryKey: []*schema.Column{TaskDependenciesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_dependencies_tasks_dependencies",
				Columns:    []*schema.Column{TaskDependenciesColumns[3]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "task_dependencies_tasks_dependents",
				Columns:    []*schema.Column{TaskDependenciesColumns[4]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taskdependency_task_id",
				Unique:  false,
				Columns: []*schema.Column{TaskDependenciesColumns[3]},
			},
			{
				Name:    "taskdependency_depends_on_id",
				Unique:  false,
				Columns: []*schema.Column{TaskDependenciesColumns[4]},
			},
			{
				Name:    "taskdependency_task_id_depends_on_id",
				Unique:  true,
				Columns: []*schema.Column{TaskDependenciesColumns[3], TaskDependenciesColumns[4]},
			},
		},
	}
	// TaskPermissionsColumns holds the columns for the "task_permissions" table.
	TaskPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "tool", Type: field.TypeString},
		{Name: "pattern", Type: field.TypeString, Nullable: true},
		{Name: "granted", Type: field.TypeBool, Default: false},
		{Name: "pre_approved", Type: field.TypeBool, Default: false},
		{Name: "manual_override", Type: field.TypeBool, Default: false},
		{Name: "decided_by", Type: field.TypeString, Nullable: true},
		{Name: "requested_at", Type: field.TypeTime},
		{Name: "decided_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "task_id", Type: field.TypeString},
	}
	// TaskPermissionsTable holds the schema information for the "task_permissions" table.
	TaskPermissionsTable = &schema.Table{
		Name:       "task_permissions",
		Columns:    TaskPermissionsColumns,
		PrimaryKey: []*schema.Column{TaskPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_permissions_tasks_permissions",
				Columns:    []*schema.Column{TaskPermissionsColumns[10]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taskpermission_task_id",
				Unique:  false,
				Columns: []*schema.Column{TaskPermissionsColumns[10]},
			},
		},
	}
	// TaskSchedulesColumns holds the columns for the "task_schedules" table.
	TaskSchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 200},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "nl_text", Type: field.TypeString, Nullable: true},
		{Name: "cron_expr", Type: field.TypeString},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "catchup", Type: field.TypeString, Default: "none"},
		{Name: "slug_prefix", Type: field.TypeString, Size: 100},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "cwd", Type: field.TypeString, Size: 4096},
		{Name: "source_branch", Type: field.TypeString, Nullable: true},
		{Name: "target_branch", Type: field.TypeString, Nullable: true},
		{Name: "priority", Type: field.TypeString, Default: "medium"},
		{Name: "current_stage", Type: field.TypeString, Default: "concept"},
		{Name: "max_iterations", Type: field.TypeInt, Default: 20},
		{Name: "token_budget", Type: field.TypeInt, Nullable: true},
		{Name: "cost_budget_cents", Type: field.TypeInt, Nullable: true},
		{Name: "stage_timeout_seconds", Type: field.TypeInt, Default: 1800},
		{Name: "silver_bullet", Type: field.TypeBool, Default: false},
		{Name: "project_id", Type: field.TypeString, Nullable: true},
		{Name: "spawner_id", Type: field.TypeString, Nullable: true},
		{Name: "permission_template", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "next_run_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_run_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_task_id", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TaskSchedulesTable holds the schema information for the "task_schedules" table.
	TaskSchedulesTable = &schema.Table{
		Name:       "task_schedules",
		Columns:    TaskSchedulesColumns,
		PrimaryKey: []*schema.Column{TaskSchedulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "taskschedule_enabled",
				Unique:  false,
				Columns: []*schema.Column{TaskSchedulesColumns[2]},
			},
			{
				Name:    "taskschedule_next_run_at",
				Unique:  false,
				Columns: []*schema.Column{TaskSchedulesColumns[24]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "provider_login", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgentCostTrendsTable,
		APIKeysTable,
		AuditEventsTable,
		DriftAlertsTable,
		EvalMetricSnapshotsTable,
		PermissionPresetsTable,
		PermissionRequestsTable,
		PipelineConfigsTable,
		ProjectsTable,
		ProjectFoldersTable,
		ProviderSettingsTable,
		RefinementTurnsTable,
		RemoteRegistrationsTable,
		SpawnersTable,
		StageRunsTable,
		SystemPromptsTable,
		TasksTable,
		TaskDependenciesTable,
		TaskPermissionsTable,
		TaskSchedulesTable,
		UsersTable,
	}
)

func init() {
	PermissionRequestsTable.ForeignKeys[0].RefTable = StageRunsTable
	ProjectFoldersTable.ForeignKeys[0].RefTable = ProjectsTable
	StageRunsTable.ForeignKeys[0].RefTable = TasksTable
	TaskDependenciesTable.ForeignKeys[0].RefTable = TasksTable
	TaskDependenciesTable.ForeignKeys[1].RefTable = TasksTable
	TaskPermissionsTable.ForeignKeys[0].RefTable = TasksTable
}
