# .golangci.yml
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gosec
    - misspell
    - gofmt

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-rules:
    - path: "_test.go"
      linters: [gosec, errcheck]
    - path: "wire_gen.go"
      linters: [all]
    - path: "ent/"
      linters: [all]

run:
  timeout: 5m
