// Code generated by ent, DO NOT EDIT.

package driftalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the driftalert type in the database.
	Label = "drift_alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpawnerID holds the string denoting the spawner_id field in the database.
	FieldSpawnerID = "spawner_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldStage holds the string denoting the stage field in the database.
	FieldStage = "stage"
	// FieldMetricKey holds the string denoting the metric_key field in the database.
	FieldMetricKey = "metric_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldBaselineValue holds the string denoting the baseline_value field in the database.
	FieldBaselineValue = "baseline_value"
	// FieldRecentValue holds the string denoting the recent_value field in the database.
	FieldRecentValue = "recent_value"
	// FieldDelta holds the string denoting the delta field in the database.
	FieldDelta = "delta"
	// FieldThreshold holds the string denoting the threshold field in the database.
	FieldThreshold = "threshold"
	// FieldSampleCount holds the string denoting the sample_count field in the database.
	FieldSampleCount = "sample_count"
	// FieldDetectedAt holds the string denoting the detected_at field in the database.
	FieldDetectedAt = "detected_at"
	// FieldAcknowledgedAt holds the string denoting the acknowledged_at field in the database.
	FieldAcknowledgedAt = "acknowledged_at"
	// Table holds the table name of the driftalert in the database.
	Table = "drift_alerts"
)

// Columns holds all SQL columns for driftalert fields.
var Columns = []string{
	FieldID,
	FieldSpawnerID,
	FieldModel,
	FieldStage,
	FieldMetricKey,
	FieldStatus,
	FieldDirection,
	FieldBaselineValue,
	FieldRecentValue,
	FieldDelta,
	FieldThreshold,
	FieldSampleCount,
	FieldDetectedAt,
	FieldAcknowledgedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultDetectedAt holds the default value on creation for the "detected_at" field.
	DefaultDetectedAt func() time.Time
)

// OrderOption defines the ordering options for the DriftAlert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpawnerID orders the results by the spawner_id field.
func BySpawnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpawnerID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByStage orders the results by the stage field.
func ByStage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStage, opts...).ToFunc()
}

// ByMetricKey orders the results by the metric_key field.
func ByMetricKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// ByBaselineValue orders the results by the baseline_value field.
func ByBaselineValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaselineValue, opts...).ToFunc()
}

// ByRecentValue orders the results by the recent_value field.
func ByRecentValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecentValue, opts...).ToFunc()
}

// ByDelta orders the results by the delta field.
func ByDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelta, opts...).ToFunc()
}

// ByThreshold orders the results by the threshold field.
func ByThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThreshold, opts...).ToFunc()
}

// BySampleCount orders the results by the sample_count field.
func BySampleCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSampleCount, opts...).ToFunc()
}

// ByDetectedAt orders the results by the detected_at field.
func ByDetectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetectedAt, opts...).ToFunc()
}

// ByAcknowledgedAt orders the results by the acknowledged_at field.
func ByAcknowledgedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcknowledgedAt, opts...).ToFunc()
}
