// Code generated by ent, DO NOT EDIT.

package agentcosttrend

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agentcosttrend type in the database.
	Label = "agent_cost_trend"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCostUsd holds the string denoting the cost_usd field in the database.
	FieldCostUsd = "cost_usd"
	// FieldRecordedAt holds the string denoting the recorded_at field in the database.
	FieldRecordedAt = "recorded_at"
	// Table holds the table name of the agentcosttrend in the database.
	Table = "agent_cost_trends"
)

// Columns holds all SQL columns for agentcosttrend fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldModel,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCostUsd,
	FieldRecordedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRecordedAt holds the default value on creation for the "recorded_at" field.
	DefaultRecordedAt func() time.Time
)

// OrderOption defines the ordering options for the AgentCostTrend queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCostUsd orders the results by the cost_usd field.
func ByCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostUsd, opts...).ToFunc()
}

// ByRecordedAt orders the results by the recorded_at field.
func ByRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordedAt, opts...).ToFunc()
}
