// Code generated by ent, DO NOT EDIT.

package agentcosttrend

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldSessionID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldModel, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldOutputTokens, v))
}

// CostUsd applies equality check predicate on the "cost_usd" field. It's identical to CostUsdEQ.
func CostUsd(v float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldCostUsd, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldRecordedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldContainsFold(FieldSessionID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldContainsFold(FieldModel, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLTE(FieldOutputTokens, v))
}

// CostUsdEQ applies the EQ predicate on the "cost_usd" field.
func CostUsdEQ(v float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldCostUsd, v))
}

// CostUsdNEQ applies the NEQ predicate on the "cost_usd" field.
func CostUsdNEQ(v float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNEQ(FieldCostUsd, v))
}

// CostUsdIn applies the In predicate on the "cost_usd" field.
func CostUsdIn(vs ...float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldIn(FieldCostUsd, vs...))
}

// CostUsdNotIn applies the NotIn predicate on the "cost_usd" field.
func CostUsdNotIn(vs ...float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNotIn(FieldCostUsd, vs...))
}

// CostUsdGT applies the GT predicate on the "cost_usd" field.
func CostUsdGT(v float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGT(FieldCostUsd, v))
}

// CostUsdGTE applies the GTE predicate on the "cost_usd" field.
func CostUsdGTE(v float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGTE(FieldCostUsd, v))
}

// CostUsdLT applies the LT predicate on the "cost_usd" field.
func CostUsdLT(v float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLT(FieldCostUsd, v))
}

// CostUsdLTE applies the LTE predicate on the "cost_usd" field.
func CostUsdLTE(v float64) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLTE(FieldCostUsd, v))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.FieldLTE(FieldRecordedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentCostTrend) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentCostTrend) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentCostTrend) predicate.AgentCostTrend {
	return predicate.AgentCostTrend(sql.NotPredicates(p))
}
