// Code generated by ent, DO NOT EDIT.

package checkpoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the checkpoint type in the database.
	Label = "checkpoint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldStageRunID holds the string denoting the stage_run_id field in the database.
	FieldStageRunID = "stage_run_id"
	// FieldSeq holds the string denoting the seq field in the database.
	FieldSeq = "seq"
	// FieldCommitSha holds the string denoting the commit_sha field in the database.
	FieldCommitSha = "commit_sha"
	// FieldTreeSha holds the string denoting the tree_sha field in the database.
	FieldTreeSha = "tree_sha"
	// FieldFilesChanged holds the string denoting the files_changed field in the database.
	FieldFilesChanged = "files_changed"
	// FieldPreRevert holds the string denoting the pre_revert field in the database.
	FieldPreRevert = "pre_revert"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the checkpoint in the database.
	Table = "checkpoints"
)

// Columns holds all SQL columns for checkpoint fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldStageRunID,
	FieldSeq,
	FieldCommitSha,
	FieldTreeSha,
	FieldFilesChanged,
	FieldPreRevert,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFilesChanged holds the default value on creation for the "files_changed" field.
	DefaultFilesChanged int
	// DefaultPreRevert holds the default value on creation for the "pre_revert" field.
	DefaultPreRevert bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Checkpoint queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByStageRunID orders the results by the stage_run_id field.
func ByStageRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageRunID, opts...).ToFunc()
}

// BySeq orders the results by the seq field.
func BySeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeq, opts...).ToFunc()
}

// ByCommitSha orders the results by the commit_sha field.
func ByCommitSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitSha, opts...).ToFunc()
}

// ByTreeSha orders the results by the tree_sha field.
func ByTreeSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTreeSha, opts...).ToFunc()
}

// ByFilesChanged orders the results by the files_changed field.
func ByFilesChanged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilesChanged, opts...).ToFunc()
}

// ByPreRevert orders the results by the pre_revert field.
func ByPreRevert(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreRevert, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
