// Code generated by Wire. DO NOT EDIT.

package main

import (
	"net/http"

	"github.com/lx-wnk/agent-dashboard/server/internal/api"
	"github.com/lx-wnk/agent-dashboard/server/internal/config"
	"github.com/lx-wnk/agent-dashboard/server/internal/sse"
)

func initializeServer(cfg config.Config) (*api.Server, *sse.Broadcaster, error) {
	broadcaster := sse.NewBroadcaster()
	routerConfig := provideRouterConfig(cfg)
	routerDeps := provideRouterDeps(routerConfig, broadcaster)
	router := api.NewRouter(routerDeps)
	server := provideServer(cfg, router)
	return server, broadcaster, nil
}

func provideRouterConfig(cfg config.Config) api.RouterConfig {
	return api.RouterConfig{
		JWTSecret: cfg.JWTSecret,
	}
}

func provideRouterDeps(cfg api.RouterConfig, b *sse.Broadcaster) api.RouterDeps {
	return api.RouterDeps{Config: cfg, AgentBroadcaster: b}
}

func provideServer(cfg config.Config, handler http.Handler) *api.Server {
	return api.NewServer(cfg.Addr(), handler, cfg.ShutdownTimeout())
}
