// Code generated by ent, DO NOT EDIT.

package capability

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the capability type in the database.
	Label = "capability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldClass holds the string denoting the class field in the database.
	FieldClass = "class"
	// FieldEnforceableBy holds the string denoting the enforceable_by field in the database.
	FieldEnforceableBy = "enforceable_by"
	// FieldRequiresPattern holds the string denoting the requires_pattern field in the database.
	FieldRequiresPattern = "requires_pattern"
	// FieldReversible holds the string denoting the reversible field in the database.
	FieldReversible = "reversible"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// Table holds the table name of the capability in the database.
	Table = "capabilities"
)

// Columns holds all SQL columns for capability fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldClass,
	FieldEnforceableBy,
	FieldRequiresPattern,
	FieldReversible,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnforceableBy holds the default value on creation for the "enforceable_by" field.
	DefaultEnforceableBy []string
	// DefaultRequiresPattern holds the default value on creation for the "requires_pattern" field.
	DefaultRequiresPattern bool
	// DefaultReversible holds the default value on creation for the "reversible" field.
	DefaultReversible bool
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
)

// OrderOption defines the ordering options for the Capability queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByClass orders the results by the class field.
func ByClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClass, opts...).ToFunc()
}

// ByRequiresPattern orders the results by the requires_pattern field.
func ByRequiresPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiresPattern, opts...).ToFunc()
}

// ByReversible orders the results by the reversible field.
func ByReversible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReversible, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}
