// Code generated by ent, DO NOT EDIT.

package permissionrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the permissionrequest type in the database.
	Label = "permission_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStageRunID holds the string denoting the stage_run_id field in the database.
	FieldStageRunID = "stage_run_id"
	// FieldTool holds the string denoting the tool field in the database.
	FieldTool = "tool"
	// FieldPattern holds the string denoting the pattern field in the database.
	FieldPattern = "pattern"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldRequestedAt holds the string denoting the requested_at field in the database.
	FieldRequestedAt = "requested_at"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// EdgeStageRun holds the string denoting the stage_run edge name in mutations.
	EdgeStageRun = "stage_run"
	// Table holds the table name of the permissionrequest in the database.
	Table = "permission_requests"
	// StageRunTable is the table that holds the stage_run relation/edge.
	StageRunTable = "permission_requests"
	// StageRunInverseTable is the table name for the StageRun entity.
	// It exists in this package in order to avoid circular dependency with the "stagerun" package.
	StageRunInverseTable = "stage_runs"
	// StageRunColumn is the table column denoting the stage_run relation/edge.
	StageRunColumn = "stage_run_id"
)

// Columns holds all SQL columns for permissionrequest fields.
var Columns = []string{
	FieldID,
	FieldStageRunID,
	FieldTool,
	FieldPattern,
	FieldReason,
	FieldOutcome,
	FieldRequestedAt,
	FieldResolvedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestedAt holds the default value on creation for the "requested_at" field.
	DefaultRequestedAt func() time.Time
)

// OrderOption defines the ordering options for the PermissionRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStageRunID orders the results by the stage_run_id field.
func ByStageRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageRunID, opts...).ToFunc()
}

// ByTool orders the results by the tool field.
func ByTool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTool, opts...).ToFunc()
}

// ByPattern orders the results by the pattern field.
func ByPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPattern, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByOutcome orders the results by the outcome field.
func ByOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcome, opts...).ToFunc()
}

// ByRequestedAt orders the results by the requested_at field.
func ByRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedAt, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByStageRunField orders the results by stage_run field.
func ByStageRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStageRunStep(), sql.OrderByField(field, opts...))
	}
}
func newStageRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StageRunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StageRunTable, StageRunColumn),
	)
}
