// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/agentcosttrend"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/apikey"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/auditlog"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionpreset"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionrequest"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/pipelineconfig"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/refinementturn"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/remoteregistration"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/stagerun"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/systemprompt"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/task"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskdependency"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskpermission"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AgentCostTrend is the client for interacting with the AgentCostTrend builders.
	AgentCostTrend *AgentCostTrendClient
	// ApiKey is the client for interacting with the ApiKey builders.
	ApiKey *ApiKeyClient
	// AuditLog is the client for interacting with the AuditLog builders.
	AuditLog *AuditLogClient
	// PermissionPreset is the client for interacting with the PermissionPreset builders.
	PermissionPreset *PermissionPresetClient
	// PermissionRequest is the client for interacting with the PermissionRequest builders.
	PermissionRequest *PermissionRequestClient
	// PipelineConfig is the client for interacting with the PipelineConfig builders.
	PipelineConfig *PipelineConfigClient
	// RefinementTurn is the client for interacting with the RefinementTurn builders.
	RefinementTurn *RefinementTurnClient
	// RemoteRegistration is the client for interacting with the RemoteRegistration builders.
	RemoteRegistration *RemoteRegistrationClient
	// StageRun is the client for interacting with the StageRun builders.
	StageRun *StageRunClient
	// SystemPrompt is the client for interacting with the SystemPrompt builders.
	SystemPrompt *SystemPromptClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// TaskDependency is the client for interacting with the TaskDependency builders.
	TaskDependency *TaskDependencyClient
	// TaskPermission is the client for interacting with the TaskPermission builders.
	TaskPermission *TaskPermissionClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AgentCostTrend = NewAgentCostTrendClient(c.config)
	c.ApiKey = NewApiKeyClient(c.config)
	c.AuditLog = NewAuditLogClient(c.config)
	c.PermissionPreset = NewPermissionPresetClient(c.config)
	c.PermissionRequest = NewPermissionRequestClient(c.config)
	c.PipelineConfig = NewPipelineConfigClient(c.config)
	c.RefinementTurn = NewRefinementTurnClient(c.config)
	c.RemoteRegistration = NewRemoteRegistrationClient(c.config)
	c.StageRun = NewStageRunClient(c.config)
	c.SystemPrompt = NewSystemPromptClient(c.config)
	c.Task = NewTaskClient(c.config)
	c.TaskDependency = NewTaskDependencyClient(c.config)
	c.TaskPermission = NewTaskPermissionClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		AgentCostTrend:     NewAgentCostTrendClient(cfg),
		ApiKey:             NewApiKeyClient(cfg),
		AuditLog:           NewAuditLogClient(cfg),
		PermissionPreset:   NewPermissionPresetClient(cfg),
		PermissionRequest:  NewPermissionRequestClient(cfg),
		PipelineConfig:     NewPipelineConfigClient(cfg),
		RefinementTurn:     NewRefinementTurnClient(cfg),
		RemoteRegistration: NewRemoteRegistrationClient(cfg),
		StageRun:           NewStageRunClient(cfg),
		SystemPrompt:       NewSystemPromptClient(cfg),
		Task:               NewTaskClient(cfg),
		TaskDependency:     NewTaskDependencyClient(cfg),
		TaskPermission:     NewTaskPermissionClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		AgentCostTrend:     NewAgentCostTrendClient(cfg),
		ApiKey:             NewApiKeyClient(cfg),
		AuditLog:           NewAuditLogClient(cfg),
		PermissionPreset:   NewPermissionPresetClient(cfg),
		PermissionRequest:  NewPermissionRequestClient(cfg),
		PipelineConfig:     NewPipelineConfigClient(cfg),
		RefinementTurn:     NewRefinementTurnClient(cfg),
		RemoteRegistration: NewRemoteRegistrationClient(cfg),
		StageRun:           NewStageRunClient(cfg),
		SystemPrompt:       NewSystemPromptClient(cfg),
		Task:               NewTaskClient(cfg),
		TaskDependency:     NewTaskDependencyClient(cfg),
		TaskPermission:     NewTaskPermissionClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AgentCostTrend.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AgentCostTrend, c.ApiKey, c.AuditLog, c.PermissionPreset, c.PermissionRequest,
		c.PipelineConfig, c.RefinementTurn, c.RemoteRegistration, c.StageRun,
		c.SystemPrompt, c.Task, c.TaskDependency, c.TaskPermission, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AgentCostTrend, c.ApiKey, c.AuditLog, c.PermissionPreset, c.PermissionRequest,
		c.PipelineConfig, c.RefinementTurn, c.RemoteRegistration, c.StageRun,
		c.SystemPrompt, c.Task, c.TaskDependency, c.TaskPermission, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AgentCostTrendMutation:
		return c.AgentCostTrend.mutate(ctx, m)
	case *ApiKeyMutation:
		return c.ApiKey.mutate(ctx, m)
	case *AuditLogMutation:
		return c.AuditLog.mutate(ctx, m)
	case *PermissionPresetMutation:
		return c.PermissionPreset.mutate(ctx, m)
	case *PermissionRequestMutation:
		return c.PermissionRequest.mutate(ctx, m)
	case *PipelineConfigMutation:
		return c.PipelineConfig.mutate(ctx, m)
	case *RefinementTurnMutation:
		return c.RefinementTurn.mutate(ctx, m)
	case *RemoteRegistrationMutation:
		return c.RemoteRegistration.mutate(ctx, m)
	case *StageRunMutation:
		return c.StageRun.mutate(ctx, m)
	case *SystemPromptMutation:
		return c.SystemPrompt.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	case *TaskDependencyMutation:
		return c.TaskDependency.mutate(ctx, m)
	case *TaskPermissionMutation:
		return c.TaskPermission.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AgentCostTrendClient is a client for the AgentCostTrend schema.
type AgentCostTrendClient struct {
	config
}

// NewAgentCostTrendClient returns a client for the AgentCostTrend from the given config.
func NewAgentCostTrendClient(c config) *AgentCostTrendClient {
	return &AgentCostTrendClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `agentcosttrend.Hooks(f(g(h())))`.
func (c *AgentCostTrendClient) Use(hooks ...Hook) {
	c.hooks.AgentCostTrend = append(c.hooks.AgentCostTrend, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `agentcosttrend.Intercept(f(g(h())))`.
func (c *AgentCostTrendClient) Intercept(interceptors ...Interceptor) {
	c.inters.AgentCostTrend = append(c.inters.AgentCostTrend, interceptors...)
}

// Create returns a builder for creating a AgentCostTrend entity.
func (c *AgentCostTrendClient) Create() *AgentCostTrendCreate {
	mutation := newAgentCostTrendMutation(c.config, OpCreate)
	return &AgentCostTrendCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AgentCostTrend entities.
func (c *AgentCostTrendClient) CreateBulk(builders ...*AgentCostTrendCreate) *AgentCostTrendCreateBulk {
	return &AgentCostTrendCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AgentCostTrendClient) MapCreateBulk(slice any, setFunc func(*AgentCostTrendCreate, int)) *AgentCostTrendCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AgentCostTrendCreateBulk{err: fmt.Errorf("calling to AgentCostTrendClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AgentCostTrendCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AgentCostTrendCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AgentCostTrend.
func (c *AgentCostTrendClient) Update() *AgentCostTrendUpdate {
	mutation := newAgentCostTrendMutation(c.config, OpUpdate)
	return &AgentCostTrendUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AgentCostTrendClient) UpdateOne(_m *AgentCostTrend) *AgentCostTrendUpdateOne {
	mutation := newAgentCostTrendMutation(c.config, OpUpdateOne, withAgentCostTrend(_m))
	return &AgentCostTrendUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AgentCostTrendClient) UpdateOneID(id string) *AgentCostTrendUpdateOne {
	mutation := newAgentCostTrendMutation(c.config, OpUpdateOne, withAgentCostTrendID(id))
	return &AgentCostTrendUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AgentCostTrend.
func (c *AgentCostTrendClient) Delete() *AgentCostTrendDelete {
	mutation := newAgentCostTrendMutation(c.config, OpDelete)
	return &AgentCostTrendDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AgentCostTrendClient) DeleteOne(_m *AgentCostTrend) *AgentCostTrendDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AgentCostTrendClient) DeleteOneID(id string) *AgentCostTrendDeleteOne {
	builder := c.Delete().Where(agentcosttrend.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AgentCostTrendDeleteOne{builder}
}

// Query returns a query builder for AgentCostTrend.
func (c *AgentCostTrendClient) Query() *AgentCostTrendQuery {
	return &AgentCostTrendQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAgentCostTrend},
		inters: c.Interceptors(),
	}
}

// Get returns a AgentCostTrend entity by its id.
func (c *AgentCostTrendClient) Get(ctx context.Context, id string) (*AgentCostTrend, error) {
	return c.Query().Where(agentcosttrend.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AgentCostTrendClient) GetX(ctx context.Context, id string) *AgentCostTrend {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AgentCostTrendClient) Hooks() []Hook {
	return c.hooks.AgentCostTrend
}

// Interceptors returns the client interceptors.
func (c *AgentCostTrendClient) Interceptors() []Interceptor {
	return c.inters.AgentCostTrend
}

func (c *AgentCostTrendClient) mutate(ctx context.Context, m *AgentCostTrendMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AgentCostTrendCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AgentCostTrendUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AgentCostTrendUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AgentCostTrendDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AgentCostTrend mutation op: %q", m.Op())
	}
}

// ApiKeyClient is a client for the ApiKey schema.
type ApiKeyClient struct {
	config
}

// NewApiKeyClient returns a client for the ApiKey from the given config.
func NewApiKeyClient(c config) *ApiKeyClient {
	return &ApiKeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `apikey.Hooks(f(g(h())))`.
func (c *ApiKeyClient) Use(hooks ...Hook) {
	c.hooks.ApiKey = append(c.hooks.ApiKey, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `apikey.Intercept(f(g(h())))`.
func (c *ApiKeyClient) Intercept(interceptors ...Interceptor) {
	c.inters.ApiKey = append(c.inters.ApiKey, interceptors...)
}

// Create returns a builder for creating a ApiKey entity.
func (c *ApiKeyClient) Create() *ApiKeyCreate {
	mutation := newApiKeyMutation(c.config, OpCreate)
	return &ApiKeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ApiKey entities.
func (c *ApiKeyClient) CreateBulk(builders ...*ApiKeyCreate) *ApiKeyCreateBulk {
	return &ApiKeyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ApiKeyClient) MapCreateBulk(slice any, setFunc func(*ApiKeyCreate, int)) *ApiKeyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ApiKeyCreateBulk{err: fmt.Errorf("calling to ApiKeyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ApiKeyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ApiKeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ApiKey.
func (c *ApiKeyClient) Update() *ApiKeyUpdate {
	mutation := newApiKeyMutation(c.config, OpUpdate)
	return &ApiKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ApiKeyClient) UpdateOne(_m *ApiKey) *ApiKeyUpdateOne {
	mutation := newApiKeyMutation(c.config, OpUpdateOne, withApiKey(_m))
	return &ApiKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ApiKeyClient) UpdateOneID(id string) *ApiKeyUpdateOne {
	mutation := newApiKeyMutation(c.config, OpUpdateOne, withApiKeyID(id))
	return &ApiKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ApiKey.
func (c *ApiKeyClient) Delete() *ApiKeyDelete {
	mutation := newApiKeyMutation(c.config, OpDelete)
	return &ApiKeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ApiKeyClient) DeleteOne(_m *ApiKey) *ApiKeyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ApiKeyClient) DeleteOneID(id string) *ApiKeyDeleteOne {
	builder := c.Delete().Where(apikey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ApiKeyDeleteOne{builder}
}

// Query returns a query builder for ApiKey.
func (c *ApiKeyClient) Query() *ApiKeyQuery {
	return &ApiKeyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeApiKey},
		inters: c.Interceptors(),
	}
}

// Get returns a ApiKey entity by its id.
func (c *ApiKeyClient) Get(ctx context.Context, id string) (*ApiKey, error) {
	return c.Query().Where(apikey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ApiKeyClient) GetX(ctx context.Context, id string) *ApiKey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ApiKeyClient) Hooks() []Hook {
	return c.hooks.ApiKey
}

// Interceptors returns the client interceptors.
func (c *ApiKeyClient) Interceptors() []Interceptor {
	return c.inters.ApiKey
}

func (c *ApiKeyClient) mutate(ctx context.Context, m *ApiKeyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ApiKeyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ApiKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ApiKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ApiKeyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ApiKey mutation op: %q", m.Op())
	}
}

// AuditLogClient is a client for the AuditLog schema.
type AuditLogClient struct {
	config
}

// NewAuditLogClient returns a client for the AuditLog from the given config.
func NewAuditLogClient(c config) *AuditLogClient {
	return &AuditLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditlog.Hooks(f(g(h())))`.
func (c *AuditLogClient) Use(hooks ...Hook) {
	c.hooks.AuditLog = append(c.hooks.AuditLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditlog.Intercept(f(g(h())))`.
func (c *AuditLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditLog = append(c.inters.AuditLog, interceptors...)
}

// Create returns a builder for creating a AuditLog entity.
func (c *AuditLogClient) Create() *AuditLogCreate {
	mutation := newAuditLogMutation(c.config, OpCreate)
	return &AuditLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditLog entities.
func (c *AuditLogClient) CreateBulk(builders ...*AuditLogCreate) *AuditLogCreateBulk {
	return &AuditLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditLogClient) MapCreateBulk(slice any, setFunc func(*AuditLogCreate, int)) *AuditLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditLogCreateBulk{err: fmt.Errorf("calling to AuditLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditLog.
func (c *AuditLogClient) Update() *AuditLogUpdate {
	mutation := newAuditLogMutation(c.config, OpUpdate)
	return &AuditLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditLogClient) UpdateOne(_m *AuditLog) *AuditLogUpdateOne {
	mutation := newAuditLogMutation(c.config, OpUpdateOne, withAuditLog(_m))
	return &AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditLogClient) UpdateOneID(id string) *AuditLogUpdateOne {
	mutation := newAuditLogMutation(c.config, OpUpdateOne, withAuditLogID(id))
	return &AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditLog.
func (c *AuditLogClient) Delete() *AuditLogDelete {
	mutation := newAuditLogMutation(c.config, OpDelete)
	return &AuditLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditLogClient) DeleteOne(_m *AuditLog) *AuditLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditLogClient) DeleteOneID(id string) *AuditLogDeleteOne {
	builder := c.Delete().Where(auditlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditLogDeleteOne{builder}
}

// Query returns a query builder for AuditLog.
func (c *AuditLogClient) Query() *AuditLogQuery {
	return &AuditLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditLog},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditLog entity by its id.
func (c *AuditLogClient) Get(ctx context.Context, id string) (*AuditLog, error) {
	return c.Query().Where(auditlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditLogClient) GetX(ctx context.Context, id string) *AuditLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a AuditLog.
func (c *AuditLogClient) QueryTask(_m *AuditLog) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(auditlog.Table, auditlog.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, auditlog.TaskTable, auditlog.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AuditLogClient) Hooks() []Hook {
	return c.hooks.AuditLog
}

// Interceptors returns the client interceptors.
func (c *AuditLogClient) Interceptors() []Interceptor {
	return c.inters.AuditLog
}

func (c *AuditLogClient) mutate(ctx context.Context, m *AuditLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditLog mutation op: %q", m.Op())
	}
}

// PermissionPresetClient is a client for the PermissionPreset schema.
type PermissionPresetClient struct {
	config
}

// NewPermissionPresetClient returns a client for the PermissionPreset from the given config.
func NewPermissionPresetClient(c config) *PermissionPresetClient {
	return &PermissionPresetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `permissionpreset.Hooks(f(g(h())))`.
func (c *PermissionPresetClient) Use(hooks ...Hook) {
	c.hooks.PermissionPreset = append(c.hooks.PermissionPreset, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `permissionpreset.Intercept(f(g(h())))`.
func (c *PermissionPresetClient) Intercept(interceptors ...Interceptor) {
	c.inters.PermissionPreset = append(c.inters.PermissionPreset, interceptors...)
}

// Create returns a builder for creating a PermissionPreset entity.
func (c *PermissionPresetClient) Create() *PermissionPresetCreate {
	mutation := newPermissionPresetMutation(c.config, OpCreate)
	return &PermissionPresetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PermissionPreset entities.
func (c *PermissionPresetClient) CreateBulk(builders ...*PermissionPresetCreate) *PermissionPresetCreateBulk {
	return &PermissionPresetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PermissionPresetClient) MapCreateBulk(slice any, setFunc func(*PermissionPresetCreate, int)) *PermissionPresetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PermissionPresetCreateBulk{err: fmt.Errorf("calling to PermissionPresetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PermissionPresetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PermissionPresetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PermissionPreset.
func (c *PermissionPresetClient) Update() *PermissionPresetUpdate {
	mutation := newPermissionPresetMutation(c.config, OpUpdate)
	return &PermissionPresetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PermissionPresetClient) UpdateOne(_m *PermissionPreset) *PermissionPresetUpdateOne {
	mutation := newPermissionPresetMutation(c.config, OpUpdateOne, withPermissionPreset(_m))
	return &PermissionPresetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PermissionPresetClient) UpdateOneID(id string) *PermissionPresetUpdateOne {
	mutation := newPermissionPresetMutation(c.config, OpUpdateOne, withPermissionPresetID(id))
	return &PermissionPresetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PermissionPreset.
func (c *PermissionPresetClient) Delete() *PermissionPresetDelete {
	mutation := newPermissionPresetMutation(c.config, OpDelete)
	return &PermissionPresetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PermissionPresetClient) DeleteOne(_m *PermissionPreset) *PermissionPresetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PermissionPresetClient) DeleteOneID(id string) *PermissionPresetDeleteOne {
	builder := c.Delete().Where(permissionpreset.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PermissionPresetDeleteOne{builder}
}

// Query returns a query builder for PermissionPreset.
func (c *PermissionPresetClient) Query() *PermissionPresetQuery {
	return &PermissionPresetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePermissionPreset},
		inters: c.Interceptors(),
	}
}

// Get returns a PermissionPreset entity by its id.
func (c *PermissionPresetClient) Get(ctx context.Context, id string) (*PermissionPreset, error) {
	return c.Query().Where(permissionpreset.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PermissionPresetClient) GetX(ctx context.Context, id string) *PermissionPreset {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PermissionPresetClient) Hooks() []Hook {
	return c.hooks.PermissionPreset
}

// Interceptors returns the client interceptors.
func (c *PermissionPresetClient) Interceptors() []Interceptor {
	return c.inters.PermissionPreset
}

func (c *PermissionPresetClient) mutate(ctx context.Context, m *PermissionPresetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PermissionPresetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PermissionPresetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PermissionPresetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PermissionPresetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PermissionPreset mutation op: %q", m.Op())
	}
}

// PermissionRequestClient is a client for the PermissionRequest schema.
type PermissionRequestClient struct {
	config
}

// NewPermissionRequestClient returns a client for the PermissionRequest from the given config.
func NewPermissionRequestClient(c config) *PermissionRequestClient {
	return &PermissionRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `permissionrequest.Hooks(f(g(h())))`.
func (c *PermissionRequestClient) Use(hooks ...Hook) {
	c.hooks.PermissionRequest = append(c.hooks.PermissionRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `permissionrequest.Intercept(f(g(h())))`.
func (c *PermissionRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.PermissionRequest = append(c.inters.PermissionRequest, interceptors...)
}

// Create returns a builder for creating a PermissionRequest entity.
func (c *PermissionRequestClient) Create() *PermissionRequestCreate {
	mutation := newPermissionRequestMutation(c.config, OpCreate)
	return &PermissionRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PermissionRequest entities.
func (c *PermissionRequestClient) CreateBulk(builders ...*PermissionRequestCreate) *PermissionRequestCreateBulk {
	return &PermissionRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PermissionRequestClient) MapCreateBulk(slice any, setFunc func(*PermissionRequestCreate, int)) *PermissionRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PermissionRequestCreateBulk{err: fmt.Errorf("calling to PermissionRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PermissionRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PermissionRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PermissionRequest.
func (c *PermissionRequestClient) Update() *PermissionRequestUpdate {
	mutation := newPermissionRequestMutation(c.config, OpUpdate)
	return &PermissionRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PermissionRequestClient) UpdateOne(_m *PermissionRequest) *PermissionRequestUpdateOne {
	mutation := newPermissionRequestMutation(c.config, OpUpdateOne, withPermissionRequest(_m))
	return &PermissionRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PermissionRequestClient) UpdateOneID(id string) *PermissionRequestUpdateOne {
	mutation := newPermissionRequestMutation(c.config, OpUpdateOne, withPermissionRequestID(id))
	return &PermissionRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PermissionRequest.
func (c *PermissionRequestClient) Delete() *PermissionRequestDelete {
	mutation := newPermissionRequestMutation(c.config, OpDelete)
	return &PermissionRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PermissionRequestClient) DeleteOne(_m *PermissionRequest) *PermissionRequestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PermissionRequestClient) DeleteOneID(id string) *PermissionRequestDeleteOne {
	builder := c.Delete().Where(permissionrequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PermissionRequestDeleteOne{builder}
}

// Query returns a query builder for PermissionRequest.
func (c *PermissionRequestClient) Query() *PermissionRequestQuery {
	return &PermissionRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePermissionRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a PermissionRequest entity by its id.
func (c *PermissionRequestClient) Get(ctx context.Context, id string) (*PermissionRequest, error) {
	return c.Query().Where(permissionrequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PermissionRequestClient) GetX(ctx context.Context, id string) *PermissionRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStageRun queries the stage_run edge of a PermissionRequest.
func (c *PermissionRequestClient) QueryStageRun(_m *PermissionRequest) *StageRunQuery {
	query := (&StageRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(permissionrequest.Table, permissionrequest.FieldID, id),
			sqlgraph.To(stagerun.Table, stagerun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, permissionrequest.StageRunTable, permissionrequest.StageRunColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PermissionRequestClient) Hooks() []Hook {
	return c.hooks.PermissionRequest
}

// Interceptors returns the client interceptors.
func (c *PermissionRequestClient) Interceptors() []Interceptor {
	return c.inters.PermissionRequest
}

func (c *PermissionRequestClient) mutate(ctx context.Context, m *PermissionRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PermissionRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PermissionRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PermissionRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PermissionRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PermissionRequest mutation op: %q", m.Op())
	}
}

// PipelineConfigClient is a client for the PipelineConfig schema.
type PipelineConfigClient struct {
	config
}

// NewPipelineConfigClient returns a client for the PipelineConfig from the given config.
func NewPipelineConfigClient(c config) *PipelineConfigClient {
	return &PipelineConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pipelineconfig.Hooks(f(g(h())))`.
func (c *PipelineConfigClient) Use(hooks ...Hook) {
	c.hooks.PipelineConfig = append(c.hooks.PipelineConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pipelineconfig.Intercept(f(g(h())))`.
func (c *PipelineConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.PipelineConfig = append(c.inters.PipelineConfig, interceptors...)
}

// Create returns a builder for creating a PipelineConfig entity.
func (c *PipelineConfigClient) Create() *PipelineConfigCreate {
	mutation := newPipelineConfigMutation(c.config, OpCreate)
	return &PipelineConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PipelineConfig entities.
func (c *PipelineConfigClient) CreateBulk(builders ...*PipelineConfigCreate) *PipelineConfigCreateBulk {
	return &PipelineConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PipelineConfigClient) MapCreateBulk(slice any, setFunc func(*PipelineConfigCreate, int)) *PipelineConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PipelineConfigCreateBulk{err: fmt.Errorf("calling to PipelineConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PipelineConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PipelineConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PipelineConfig.
func (c *PipelineConfigClient) Update() *PipelineConfigUpdate {
	mutation := newPipelineConfigMutation(c.config, OpUpdate)
	return &PipelineConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PipelineConfigClient) UpdateOne(_m *PipelineConfig) *PipelineConfigUpdateOne {
	mutation := newPipelineConfigMutation(c.config, OpUpdateOne, withPipelineConfig(_m))
	return &PipelineConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PipelineConfigClient) UpdateOneID(id string) *PipelineConfigUpdateOne {
	mutation := newPipelineConfigMutation(c.config, OpUpdateOne, withPipelineConfigID(id))
	return &PipelineConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PipelineConfig.
func (c *PipelineConfigClient) Delete() *PipelineConfigDelete {
	mutation := newPipelineConfigMutation(c.config, OpDelete)
	return &PipelineConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PipelineConfigClient) DeleteOne(_m *PipelineConfig) *PipelineConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PipelineConfigClient) DeleteOneID(id string) *PipelineConfigDeleteOne {
	builder := c.Delete().Where(pipelineconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PipelineConfigDeleteOne{builder}
}

// Query returns a query builder for PipelineConfig.
func (c *PipelineConfigClient) Query() *PipelineConfigQuery {
	return &PipelineConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePipelineConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a PipelineConfig entity by its id.
func (c *PipelineConfigClient) Get(ctx context.Context, id string) (*PipelineConfig, error) {
	return c.Query().Where(pipelineconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PipelineConfigClient) GetX(ctx context.Context, id string) *PipelineConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PipelineConfigClient) Hooks() []Hook {
	return c.hooks.PipelineConfig
}

// Interceptors returns the client interceptors.
func (c *PipelineConfigClient) Interceptors() []Interceptor {
	return c.inters.PipelineConfig
}

func (c *PipelineConfigClient) mutate(ctx context.Context, m *PipelineConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PipelineConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PipelineConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PipelineConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PipelineConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PipelineConfig mutation op: %q", m.Op())
	}
}

// RefinementTurnClient is a client for the RefinementTurn schema.
type RefinementTurnClient struct {
	config
}

// NewRefinementTurnClient returns a client for the RefinementTurn from the given config.
func NewRefinementTurnClient(c config) *RefinementTurnClient {
	return &RefinementTurnClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refinementturn.Hooks(f(g(h())))`.
func (c *RefinementTurnClient) Use(hooks ...Hook) {
	c.hooks.RefinementTurn = append(c.hooks.RefinementTurn, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refinementturn.Intercept(f(g(h())))`.
func (c *RefinementTurnClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefinementTurn = append(c.inters.RefinementTurn, interceptors...)
}

// Create returns a builder for creating a RefinementTurn entity.
func (c *RefinementTurnClient) Create() *RefinementTurnCreate {
	mutation := newRefinementTurnMutation(c.config, OpCreate)
	return &RefinementTurnCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefinementTurn entities.
func (c *RefinementTurnClient) CreateBulk(builders ...*RefinementTurnCreate) *RefinementTurnCreateBulk {
	return &RefinementTurnCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefinementTurnClient) MapCreateBulk(slice any, setFunc func(*RefinementTurnCreate, int)) *RefinementTurnCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefinementTurnCreateBulk{err: fmt.Errorf("calling to RefinementTurnClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefinementTurnCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefinementTurnCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefinementTurn.
func (c *RefinementTurnClient) Update() *RefinementTurnUpdate {
	mutation := newRefinementTurnMutation(c.config, OpUpdate)
	return &RefinementTurnUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefinementTurnClient) UpdateOne(_m *RefinementTurn) *RefinementTurnUpdateOne {
	mutation := newRefinementTurnMutation(c.config, OpUpdateOne, withRefinementTurn(_m))
	return &RefinementTurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefinementTurnClient) UpdateOneID(id string) *RefinementTurnUpdateOne {
	mutation := newRefinementTurnMutation(c.config, OpUpdateOne, withRefinementTurnID(id))
	return &RefinementTurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefinementTurn.
func (c *RefinementTurnClient) Delete() *RefinementTurnDelete {
	mutation := newRefinementTurnMutation(c.config, OpDelete)
	return &RefinementTurnDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefinementTurnClient) DeleteOne(_m *RefinementTurn) *RefinementTurnDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefinementTurnClient) DeleteOneID(id string) *RefinementTurnDeleteOne {
	builder := c.Delete().Where(refinementturn.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefinementTurnDeleteOne{builder}
}

// Query returns a query builder for RefinementTurn.
func (c *RefinementTurnClient) Query() *RefinementTurnQuery {
	return &RefinementTurnQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefinementTurn},
		inters: c.Interceptors(),
	}
}

// Get returns a RefinementTurn entity by its id.
func (c *RefinementTurnClient) Get(ctx context.Context, id string) (*RefinementTurn, error) {
	return c.Query().Where(refinementturn.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RefinementTurnClient) GetX(ctx context.Context, id string) *RefinementTurn {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RefinementTurnClient) Hooks() []Hook {
	return c.hooks.RefinementTurn
}

// Interceptors returns the client interceptors.
func (c *RefinementTurnClient) Interceptors() []Interceptor {
	return c.inters.RefinementTurn
}

func (c *RefinementTurnClient) mutate(ctx context.Context, m *RefinementTurnMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefinementTurnCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefinementTurnUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefinementTurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefinementTurnDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefinementTurn mutation op: %q", m.Op())
	}
}

// RemoteRegistrationClient is a client for the RemoteRegistration schema.
type RemoteRegistrationClient struct {
	config
}

// NewRemoteRegistrationClient returns a client for the RemoteRegistration from the given config.
func NewRemoteRegistrationClient(c config) *RemoteRegistrationClient {
	return &RemoteRegistrationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `remoteregistration.Hooks(f(g(h())))`.
func (c *RemoteRegistrationClient) Use(hooks ...Hook) {
	c.hooks.RemoteRegistration = append(c.hooks.RemoteRegistration, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `remoteregistration.Intercept(f(g(h())))`.
func (c *RemoteRegistrationClient) Intercept(interceptors ...Interceptor) {
	c.inters.RemoteRegistration = append(c.inters.RemoteRegistration, interceptors...)
}

// Create returns a builder for creating a RemoteRegistration entity.
func (c *RemoteRegistrationClient) Create() *RemoteRegistrationCreate {
	mutation := newRemoteRegistrationMutation(c.config, OpCreate)
	return &RemoteRegistrationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RemoteRegistration entities.
func (c *RemoteRegistrationClient) CreateBulk(builders ...*RemoteRegistrationCreate) *RemoteRegistrationCreateBulk {
	return &RemoteRegistrationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RemoteRegistrationClient) MapCreateBulk(slice any, setFunc func(*RemoteRegistrationCreate, int)) *RemoteRegistrationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RemoteRegistrationCreateBulk{err: fmt.Errorf("calling to RemoteRegistrationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RemoteRegistrationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RemoteRegistrationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RemoteRegistration.
func (c *RemoteRegistrationClient) Update() *RemoteRegistrationUpdate {
	mutation := newRemoteRegistrationMutation(c.config, OpUpdate)
	return &RemoteRegistrationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RemoteRegistrationClient) UpdateOne(_m *RemoteRegistration) *RemoteRegistrationUpdateOne {
	mutation := newRemoteRegistrationMutation(c.config, OpUpdateOne, withRemoteRegistration(_m))
	return &RemoteRegistrationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RemoteRegistrationClient) UpdateOneID(id string) *RemoteRegistrationUpdateOne {
	mutation := newRemoteRegistrationMutation(c.config, OpUpdateOne, withRemoteRegistrationID(id))
	return &RemoteRegistrationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RemoteRegistration.
func (c *RemoteRegistrationClient) Delete() *RemoteRegistrationDelete {
	mutation := newRemoteRegistrationMutation(c.config, OpDelete)
	return &RemoteRegistrationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RemoteRegistrationClient) DeleteOne(_m *RemoteRegistration) *RemoteRegistrationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RemoteRegistrationClient) DeleteOneID(id string) *RemoteRegistrationDeleteOne {
	builder := c.Delete().Where(remoteregistration.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RemoteRegistrationDeleteOne{builder}
}

// Query returns a query builder for RemoteRegistration.
func (c *RemoteRegistrationClient) Query() *RemoteRegistrationQuery {
	return &RemoteRegistrationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRemoteRegistration},
		inters: c.Interceptors(),
	}
}

// Get returns a RemoteRegistration entity by its id.
func (c *RemoteRegistrationClient) Get(ctx context.Context, id string) (*RemoteRegistration, error) {
	return c.Query().Where(remoteregistration.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RemoteRegistrationClient) GetX(ctx context.Context, id string) *RemoteRegistration {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RemoteRegistrationClient) Hooks() []Hook {
	return c.hooks.RemoteRegistration
}

// Interceptors returns the client interceptors.
func (c *RemoteRegistrationClient) Interceptors() []Interceptor {
	return c.inters.RemoteRegistration
}

func (c *RemoteRegistrationClient) mutate(ctx context.Context, m *RemoteRegistrationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RemoteRegistrationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RemoteRegistrationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RemoteRegistrationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RemoteRegistrationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RemoteRegistration mutation op: %q", m.Op())
	}
}

// StageRunClient is a client for the StageRun schema.
type StageRunClient struct {
	config
}

// NewStageRunClient returns a client for the StageRun from the given config.
func NewStageRunClient(c config) *StageRunClient {
	return &StageRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `stagerun.Hooks(f(g(h())))`.
func (c *StageRunClient) Use(hooks ...Hook) {
	c.hooks.StageRun = append(c.hooks.StageRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `stagerun.Intercept(f(g(h())))`.
func (c *StageRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.StageRun = append(c.inters.StageRun, interceptors...)
}

// Create returns a builder for creating a StageRun entity.
func (c *StageRunClient) Create() *StageRunCreate {
	mutation := newStageRunMutation(c.config, OpCreate)
	return &StageRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StageRun entities.
func (c *StageRunClient) CreateBulk(builders ...*StageRunCreate) *StageRunCreateBulk {
	return &StageRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StageRunClient) MapCreateBulk(slice any, setFunc func(*StageRunCreate, int)) *StageRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StageRunCreateBulk{err: fmt.Errorf("calling to StageRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StageRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StageRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StageRun.
func (c *StageRunClient) Update() *StageRunUpdate {
	mutation := newStageRunMutation(c.config, OpUpdate)
	return &StageRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StageRunClient) UpdateOne(_m *StageRun) *StageRunUpdateOne {
	mutation := newStageRunMutation(c.config, OpUpdateOne, withStageRun(_m))
	return &StageRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StageRunClient) UpdateOneID(id string) *StageRunUpdateOne {
	mutation := newStageRunMutation(c.config, OpUpdateOne, withStageRunID(id))
	return &StageRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StageRun.
func (c *StageRunClient) Delete() *StageRunDelete {
	mutation := newStageRunMutation(c.config, OpDelete)
	return &StageRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StageRunClient) DeleteOne(_m *StageRun) *StageRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StageRunClient) DeleteOneID(id string) *StageRunDeleteOne {
	builder := c.Delete().Where(stagerun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StageRunDeleteOne{builder}
}

// Query returns a query builder for StageRun.
func (c *StageRunClient) Query() *StageRunQuery {
	return &StageRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStageRun},
		inters: c.Interceptors(),
	}
}

// Get returns a StageRun entity by its id.
func (c *StageRunClient) Get(ctx context.Context, id string) (*StageRun, error) {
	return c.Query().Where(stagerun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StageRunClient) GetX(ctx context.Context, id string) *StageRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a StageRun.
func (c *StageRunClient) QueryTask(_m *StageRun) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stagerun.Table, stagerun.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stagerun.TaskTable, stagerun.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPermissionRequests queries the permission_requests edge of a StageRun.
func (c *StageRunClient) QueryPermissionRequests(_m *StageRun) *PermissionRequestQuery {
	query := (&PermissionRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stagerun.Table, stagerun.FieldID, id),
			sqlgraph.To(permissionrequest.Table, permissionrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, stagerun.PermissionRequestsTable, stagerun.PermissionRequestsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StageRunClient) Hooks() []Hook {
	return c.hooks.StageRun
}

// Interceptors returns the client interceptors.
func (c *StageRunClient) Interceptors() []Interceptor {
	return c.inters.StageRun
}

func (c *StageRunClient) mutate(ctx context.Context, m *StageRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StageRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StageRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StageRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StageRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown StageRun mutation op: %q", m.Op())
	}
}

// SystemPromptClient is a client for the SystemPrompt schema.
type SystemPromptClient struct {
	config
}

// NewSystemPromptClient returns a client for the SystemPrompt from the given config.
func NewSystemPromptClient(c config) *SystemPromptClient {
	return &SystemPromptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `systemprompt.Hooks(f(g(h())))`.
func (c *SystemPromptClient) Use(hooks ...Hook) {
	c.hooks.SystemPrompt = append(c.hooks.SystemPrompt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `systemprompt.Intercept(f(g(h())))`.
func (c *SystemPromptClient) Intercept(interceptors ...Interceptor) {
	c.inters.SystemPrompt = append(c.inters.SystemPrompt, interceptors...)
}

// Create returns a builder for creating a SystemPrompt entity.
func (c *SystemPromptClient) Create() *SystemPromptCreate {
	mutation := newSystemPromptMutation(c.config, OpCreate)
	return &SystemPromptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SystemPrompt entities.
func (c *SystemPromptClient) CreateBulk(builders ...*SystemPromptCreate) *SystemPromptCreateBulk {
	return &SystemPromptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SystemPromptClient) MapCreateBulk(slice any, setFunc func(*SystemPromptCreate, int)) *SystemPromptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SystemPromptCreateBulk{err: fmt.Errorf("calling to SystemPromptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SystemPromptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SystemPromptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SystemPrompt.
func (c *SystemPromptClient) Update() *SystemPromptUpdate {
	mutation := newSystemPromptMutation(c.config, OpUpdate)
	return &SystemPromptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SystemPromptClient) UpdateOne(_m *SystemPrompt) *SystemPromptUpdateOne {
	mutation := newSystemPromptMutation(c.config, OpUpdateOne, withSystemPrompt(_m))
	return &SystemPromptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SystemPromptClient) UpdateOneID(id string) *SystemPromptUpdateOne {
	mutation := newSystemPromptMutation(c.config, OpUpdateOne, withSystemPromptID(id))
	return &SystemPromptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SystemPrompt.
func (c *SystemPromptClient) Delete() *SystemPromptDelete {
	mutation := newSystemPromptMutation(c.config, OpDelete)
	return &SystemPromptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SystemPromptClient) DeleteOne(_m *SystemPrompt) *SystemPromptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SystemPromptClient) DeleteOneID(id string) *SystemPromptDeleteOne {
	builder := c.Delete().Where(systemprompt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SystemPromptDeleteOne{builder}
}

// Query returns a query builder for SystemPrompt.
func (c *SystemPromptClient) Query() *SystemPromptQuery {
	return &SystemPromptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSystemPrompt},
		inters: c.Interceptors(),
	}
}

// Get returns a SystemPrompt entity by its id.
func (c *SystemPromptClient) Get(ctx context.Context, id string) (*SystemPrompt, error) {
	return c.Query().Where(systemprompt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SystemPromptClient) GetX(ctx context.Context, id string) *SystemPrompt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SystemPromptClient) Hooks() []Hook {
	return c.hooks.SystemPrompt
}

// Interceptors returns the client interceptors.
func (c *SystemPromptClient) Interceptors() []Interceptor {
	return c.inters.SystemPrompt
}

func (c *SystemPromptClient) mutate(ctx context.Context, m *SystemPromptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SystemPromptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SystemPromptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SystemPromptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SystemPromptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SystemPrompt mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id string) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id string) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id string) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id string) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStageRuns queries the stage_runs edge of a Task.
func (c *TaskClient) QueryStageRuns(_m *Task) *StageRunQuery {
	query := (&StageRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(stagerun.Table, stagerun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.StageRunsTable, task.StageRunsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPermissions queries the permissions edge of a Task.
func (c *TaskClient) QueryPermissions(_m *Task) *TaskPermissionQuery {
	query := (&TaskPermissionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(taskpermission.Table, taskpermission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.PermissionsTable, task.PermissionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAuditLogs queries the audit_logs edge of a Task.
func (c *TaskClient) QueryAuditLogs(_m *Task) *AuditLogQuery {
	query := (&AuditLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(auditlog.Table, auditlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.AuditLogsTable, task.AuditLogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDependencies queries the dependencies edge of a Task.
func (c *TaskClient) QueryDependencies(_m *Task) *TaskDependencyQuery {
	query := (&TaskDependencyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(taskdependency.Table, taskdependency.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.DependenciesTable, task.DependenciesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDependents queries the dependents edge of a Task.
func (c *TaskClient) QueryDependents(_m *Task) *TaskDependencyQuery {
	query := (&TaskDependencyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(taskdependency.Table, taskdependency.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.DependentsTable, task.DependentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// TaskDependencyClient is a client for the TaskDependency schema.
type TaskDependencyClient struct {
	config
}

// NewTaskDependencyClient returns a client for the TaskDependency from the given config.
func NewTaskDependencyClient(c config) *TaskDependencyClient {
	return &TaskDependencyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `taskdependency.Hooks(f(g(h())))`.
func (c *TaskDependencyClient) Use(hooks ...Hook) {
	c.hooks.TaskDependency = append(c.hooks.TaskDependency, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `taskdependency.Intercept(f(g(h())))`.
func (c *TaskDependencyClient) Intercept(interceptors ...Interceptor) {
	c.inters.TaskDependency = append(c.inters.TaskDependency, interceptors...)
}

// Create returns a builder for creating a TaskDependency entity.
func (c *TaskDependencyClient) Create() *TaskDependencyCreate {
	mutation := newTaskDependencyMutation(c.config, OpCreate)
	return &TaskDependencyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TaskDependency entities.
func (c *TaskDependencyClient) CreateBulk(builders ...*TaskDependencyCreate) *TaskDependencyCreateBulk {
	return &TaskDependencyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskDependencyClient) MapCreateBulk(slice any, setFunc func(*TaskDependencyCreate, int)) *TaskDependencyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskDependencyCreateBulk{err: fmt.Errorf("calling to TaskDependencyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskDependencyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskDependencyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TaskDependency.
func (c *TaskDependencyClient) Update() *TaskDependencyUpdate {
	mutation := newTaskDependencyMutation(c.config, OpUpdate)
	return &TaskDependencyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskDependencyClient) UpdateOne(_m *TaskDependency) *TaskDependencyUpdateOne {
	mutation := newTaskDependencyMutation(c.config, OpUpdateOne, withTaskDependency(_m))
	return &TaskDependencyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskDependencyClient) UpdateOneID(id string) *TaskDependencyUpdateOne {
	mutation := newTaskDependencyMutation(c.config, OpUpdateOne, withTaskDependencyID(id))
	return &TaskDependencyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TaskDependency.
func (c *TaskDependencyClient) Delete() *TaskDependencyDelete {
	mutation := newTaskDependencyMutation(c.config, OpDelete)
	return &TaskDependencyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskDependencyClient) DeleteOne(_m *TaskDependency) *TaskDependencyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskDependencyClient) DeleteOneID(id string) *TaskDependencyDeleteOne {
	builder := c.Delete().Where(taskdependency.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDependencyDeleteOne{builder}
}

// Query returns a query builder for TaskDependency.
func (c *TaskDependencyClient) Query() *TaskDependencyQuery {
	return &TaskDependencyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTaskDependency},
		inters: c.Interceptors(),
	}
}

// Get returns a TaskDependency entity by its id.
func (c *TaskDependencyClient) Get(ctx context.Context, id string) (*TaskDependency, error) {
	return c.Query().Where(taskdependency.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskDependencyClient) GetX(ctx context.Context, id string) *TaskDependency {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a TaskDependency.
func (c *TaskDependencyClient) QueryTask(_m *TaskDependency) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taskdependency.Table, taskdependency.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskdependency.TaskTable, taskdependency.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDependsOn queries the depends_on edge of a TaskDependency.
func (c *TaskDependencyClient) QueryDependsOn(_m *TaskDependency) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taskdependency.Table, taskdependency.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskdependency.DependsOnTable, taskdependency.DependsOnColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskDependencyClient) Hooks() []Hook {
	return c.hooks.TaskDependency
}

// Interceptors returns the client interceptors.
func (c *TaskDependencyClient) Interceptors() []Interceptor {
	return c.inters.TaskDependency
}

func (c *TaskDependencyClient) mutate(ctx context.Context, m *TaskDependencyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskDependencyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskDependencyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskDependencyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDependencyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TaskDependency mutation op: %q", m.Op())
	}
}

// TaskPermissionClient is a client for the TaskPermission schema.
type TaskPermissionClient struct {
	config
}

// NewTaskPermissionClient returns a client for the TaskPermission from the given config.
func NewTaskPermissionClient(c config) *TaskPermissionClient {
	return &TaskPermissionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `taskpermission.Hooks(f(g(h())))`.
func (c *TaskPermissionClient) Use(hooks ...Hook) {
	c.hooks.TaskPermission = append(c.hooks.TaskPermission, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `taskpermission.Intercept(f(g(h())))`.
func (c *TaskPermissionClient) Intercept(interceptors ...Interceptor) {
	c.inters.TaskPermission = append(c.inters.TaskPermission, interceptors...)
}

// Create returns a builder for creating a TaskPermission entity.
func (c *TaskPermissionClient) Create() *TaskPermissionCreate {
	mutation := newTaskPermissionMutation(c.config, OpCreate)
	return &TaskPermissionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TaskPermission entities.
func (c *TaskPermissionClient) CreateBulk(builders ...*TaskPermissionCreate) *TaskPermissionCreateBulk {
	return &TaskPermissionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskPermissionClient) MapCreateBulk(slice any, setFunc func(*TaskPermissionCreate, int)) *TaskPermissionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskPermissionCreateBulk{err: fmt.Errorf("calling to TaskPermissionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskPermissionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskPermissionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TaskPermission.
func (c *TaskPermissionClient) Update() *TaskPermissionUpdate {
	mutation := newTaskPermissionMutation(c.config, OpUpdate)
	return &TaskPermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskPermissionClient) UpdateOne(_m *TaskPermission) *TaskPermissionUpdateOne {
	mutation := newTaskPermissionMutation(c.config, OpUpdateOne, withTaskPermission(_m))
	return &TaskPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskPermissionClient) UpdateOneID(id string) *TaskPermissionUpdateOne {
	mutation := newTaskPermissionMutation(c.config, OpUpdateOne, withTaskPermissionID(id))
	return &TaskPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TaskPermission.
func (c *TaskPermissionClient) Delete() *TaskPermissionDelete {
	mutation := newTaskPermissionMutation(c.config, OpDelete)
	return &TaskPermissionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskPermissionClient) DeleteOne(_m *TaskPermission) *TaskPermissionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskPermissionClient) DeleteOneID(id string) *TaskPermissionDeleteOne {
	builder := c.Delete().Where(taskpermission.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskPermissionDeleteOne{builder}
}

// Query returns a query builder for TaskPermission.
func (c *TaskPermissionClient) Query() *TaskPermissionQuery {
	return &TaskPermissionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTaskPermission},
		inters: c.Interceptors(),
	}
}

// Get returns a TaskPermission entity by its id.
func (c *TaskPermissionClient) Get(ctx context.Context, id string) (*TaskPermission, error) {
	return c.Query().Where(taskpermission.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskPermissionClient) GetX(ctx context.Context, id string) *TaskPermission {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a TaskPermission.
func (c *TaskPermissionClient) QueryTask(_m *TaskPermission) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taskpermission.Table, taskpermission.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskpermission.TaskTable, taskpermission.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskPermissionClient) Hooks() []Hook {
	return c.hooks.TaskPermission
}

// Interceptors returns the client interceptors.
func (c *TaskPermissionClient) Interceptors() []Interceptor {
	return c.inters.TaskPermission
}

func (c *TaskPermissionClient) mutate(ctx context.Context, m *TaskPermissionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskPermissionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskPermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskPermissionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TaskPermission mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id string) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id string) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id string) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id string) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AgentCostTrend, ApiKey, AuditLog, PermissionPreset, PermissionRequest,
		PipelineConfig, RefinementTurn, RemoteRegistration, StageRun, SystemPrompt,
		Task, TaskDependency, TaskPermission, User []ent.Hook
	}
	inters struct {
		AgentCostTrend, ApiKey, AuditLog, PermissionPreset, PermissionRequest,
		PipelineConfig, RefinementTurn, RemoteRegistration, StageRun, SystemPrompt,
		Task, TaskDependency, TaskPermission, User []ent.Interceptor
	}
)
