// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionrequest"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/stagerun"
)

// PermissionRequestCreate is the builder for creating a PermissionRequest entity.
type PermissionRequestCreate struct {
	config
	mutation *PermissionRequestMutation
	hooks    []Hook
}

// SetStageRunID sets the "stage_run_id" field.
func (_c *PermissionRequestCreate) SetStageRunID(v string) *PermissionRequestCreate {
	_c.mutation.SetStageRunID(v)
	return _c
}

// SetTool sets the "tool" field.
func (_c *PermissionRequestCreate) SetTool(v string) *PermissionRequestCreate {
	_c.mutation.SetTool(v)
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *PermissionRequestCreate) SetPattern(v string) *PermissionRequestCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillablePattern(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetPattern(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *PermissionRequestCreate) SetReason(v string) *PermissionRequestCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableReason(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *PermissionRequestCreate) SetOutcome(v string) *PermissionRequestCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableOutcome(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetOutcome(*v)
	}
	return _c
}

// SetRequestedAt sets the "requested_at" field.
func (_c *PermissionRequestCreate) SetRequestedAt(v time.Time) *PermissionRequestCreate {
	_c.mutation.SetRequestedAt(v)
	return _c
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableRequestedAt(v *time.Time) *PermissionRequestCreate {
	if v != nil {
		_c.SetRequestedAt(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *PermissionRequestCreate) SetResolvedAt(v time.Time) *PermissionRequestCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableResolvedAt(v *time.Time) *PermissionRequestCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionRequestCreate) SetID(v string) *PermissionRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetStageRun sets the "stage_run" edge to the StageRun entity.
func (_c *PermissionRequestCreate) SetStageRun(v *StageRun) *PermissionRequestCreate {
	return _c.SetStageRunID(v.ID)
}

// Mutation returns the PermissionRequestMutation object of the builder.
func (_c *PermissionRequestCreate) Mutation() *PermissionRequestMutation {
	return _c.mutation
}

// Save creates the PermissionRequest in the database.
func (_c *PermissionRequestCreate) Save(ctx context.Context) (*PermissionRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionRequestCreate) SaveX(ctx context.Context) *PermissionRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PermissionRequestCreate) defaults() {
	if _, ok := _c.mutation.RequestedAt(); !ok {
		v := permissionrequest.DefaultRequestedAt()
		_c.mutation.SetRequestedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionRequestCreate) check() error {
	if _, ok := _c.mutation.StageRunID(); !ok {
		return &ValidationError{Name: "stage_run_id", err: errors.New(`ent: missing required field "PermissionRequest.stage_run_id"`)}
	}
	if _, ok := _c.mutation.Tool(); !ok {
		return &ValidationError{Name: "tool", err: errors.New(`ent: missing required field "PermissionRequest.tool"`)}
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "PermissionRequest.requested_at"`)}
	}
	if len(_c.mutation.StageRunIDs()) == 0 {
		return &ValidationError{Name: "stage_run", err: errors.New(`ent: missing required edge "PermissionRequest.stage_run"`)}
	}
	return nil
}

func (_c *PermissionRequestCreate) sqlSave(ctx context.Context) (*PermissionRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PermissionRequest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionRequestCreate) createSpec() (*PermissionRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &PermissionRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permissionrequest.Table, sqlgraph.NewFieldSpec(permissionrequest.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Tool(); ok {
		_spec.SetField(permissionrequest.FieldTool, field.TypeString, value)
		_node.Tool = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(permissionrequest.FieldPattern, field.TypeString, value)
		_node.Pattern = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(permissionrequest.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(permissionrequest.FieldOutcome, field.TypeString, value)
		_node.Outcome = &value
	}
	if value, ok := _c.mutation.RequestedAt(); ok {
		_spec.SetField(permissionrequest.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(permissionrequest.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if nodes := _c.mutation.StageRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissionrequest.StageRunTable,
			Columns: []string{permissionrequest.StageRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stagerun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StageRunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PermissionRequestCreateBulk is the builder for creating many PermissionRequest entities in bulk.
type PermissionRequestCreateBulk struct {
	config
	err      error
	builders []*PermissionRequestCreate
}

// Save creates the PermissionRequest entities in the database.
func (_c *PermissionRequestCreateBulk) Save(ctx context.Context) ([]*PermissionRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PermissionRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionRequestCreateBulk) SaveX(ctx context.Context) []*PermissionRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
