// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionpreset"
)

// PermissionPresetCreate is the builder for creating a PermissionPreset entity.
type PermissionPresetCreate struct {
	config
	mutation *PermissionPresetMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PermissionPresetCreate) SetUserID(v string) *PermissionPresetCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *PermissionPresetCreate) SetNillableUserID(v *string) *PermissionPresetCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetProjectCwd sets the "project_cwd" field.
func (_c *PermissionPresetCreate) SetProjectCwd(v string) *PermissionPresetCreate {
	_c.mutation.SetProjectCwd(v)
	return _c
}

// SetTool sets the "tool" field.
func (_c *PermissionPresetCreate) SetTool(v string) *PermissionPresetCreate {
	_c.mutation.SetTool(v)
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *PermissionPresetCreate) SetPattern(v string) *PermissionPresetCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_c *PermissionPresetCreate) SetNillablePattern(v *string) *PermissionPresetCreate {
	if v != nil {
		_c.SetPattern(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionPresetCreate) SetID(v string) *PermissionPresetCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PermissionPresetMutation object of the builder.
func (_c *PermissionPresetCreate) Mutation() *PermissionPresetMutation {
	return _c.mutation
}

// Save creates the PermissionPreset in the database.
func (_c *PermissionPresetCreate) Save(ctx context.Context) (*PermissionPreset, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionPresetCreate) SaveX(ctx context.Context) *PermissionPreset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionPresetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionPresetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionPresetCreate) check() error {
	if _, ok := _c.mutation.ProjectCwd(); !ok {
		return &ValidationError{Name: "project_cwd", err: errors.New(`ent: missing required field "PermissionPreset.project_cwd"`)}
	}
	if _, ok := _c.mutation.Tool(); !ok {
		return &ValidationError{Name: "tool", err: errors.New(`ent: missing required field "PermissionPreset.tool"`)}
	}
	return nil
}

func (_c *PermissionPresetCreate) sqlSave(ctx context.Context) (*PermissionPreset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PermissionPreset.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionPresetCreate) createSpec() (*PermissionPreset, *sqlgraph.CreateSpec) {
	var (
		_node = &PermissionPreset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permissionpreset.Table, sqlgraph.NewFieldSpec(permissionpreset.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(permissionpreset.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.ProjectCwd(); ok {
		_spec.SetField(permissionpreset.FieldProjectCwd, field.TypeString, value)
		_node.ProjectCwd = value
	}
	if value, ok := _c.mutation.Tool(); ok {
		_spec.SetField(permissionpreset.FieldTool, field.TypeString, value)
		_node.Tool = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(permissionpreset.FieldPattern, field.TypeString, value)
		_node.Pattern = &value
	}
	return _node, _spec
}

// PermissionPresetCreateBulk is the builder for creating many PermissionPreset entities in bulk.
type PermissionPresetCreateBulk struct {
	config
	err      error
	builders []*PermissionPresetCreate
}

// Save creates the PermissionPreset entities in the database.
func (_c *PermissionPresetCreateBulk) Save(ctx context.Context) ([]*PermissionPreset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PermissionPreset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionPresetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionPresetCreateBulk) SaveX(ctx context.Context) []*PermissionPreset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionPresetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionPresetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
