// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/projectfolder"
)

// ProjectFolderCreate is the builder for creating a ProjectFolder entity.
type ProjectFolderCreate struct {
	config
	mutation *ProjectFolderMutation
	hooks    []Hook
}

// SetPath sets the "path" field.
func (_c *ProjectFolderCreate) SetPath(v string) *ProjectFolderCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *ProjectFolderCreate) SetLabel(v string) *ProjectFolderCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *ProjectFolderCreate) SetNillableLabel(v *string) *ProjectFolderCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *ProjectFolderCreate) SetIsDefault(v bool) *ProjectFolderCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *ProjectFolderCreate) SetNillableIsDefault(v *bool) *ProjectFolderCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectFolderCreate) SetCreatedAt(v time.Time) *ProjectFolderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectFolderCreate) SetNillableCreatedAt(v *time.Time) *ProjectFolderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectFolderCreate) SetID(v string) *ProjectFolderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *ProjectFolderCreate) SetProjectID(id string) *ProjectFolderCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectFolderCreate) SetProject(v *Project) *ProjectFolderCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the ProjectFolderMutation object of the builder.
func (_c *ProjectFolderCreate) Mutation() *ProjectFolderMutation {
	return _c.mutation
}

// Save creates the ProjectFolder in the database.
func (_c *ProjectFolderCreate) Save(ctx context.Context) (*ProjectFolder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectFolderCreate) SaveX(ctx context.Context) *ProjectFolder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectFolderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectFolderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectFolderCreate) defaults() {
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := projectfolder.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectfolder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectFolderCreate) check() error {
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "ProjectFolder.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := projectfolder.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ProjectFolder.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "ProjectFolder.is_default"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectFolder.created_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectFolder.project"`)}
	}
	return nil
}

func (_c *ProjectFolderCreate) sqlSave(ctx context.Context) (*ProjectFolder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProjectFolder.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectFolderCreate) createSpec() (*ProjectFolder, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectFolder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectfolder.Table, sqlgraph.NewFieldSpec(projectfolder.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(projectfolder.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(projectfolder.FieldLabel, field.TypeString, value)
		_node.Label = &value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(projectfolder.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectfolder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectfolder.ProjectTable,
			Columns: []string{projectfolder.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_folders = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectFolderCreateBulk is the builder for creating many ProjectFolder entities in bulk.
type ProjectFolderCreateBulk struct {
	config
	err      error
	builders []*ProjectFolderCreate
}

// Save creates the ProjectFolder entities in the database.
func (_c *ProjectFolderCreateBulk) Save(ctx context.Context) ([]*ProjectFolder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectFolder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectFolderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectFolderCreateBulk) SaveX(ctx context.Context) []*ProjectFolder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectFolderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectFolderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
