// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/refinementturn"
)

// RefinementTurnCreate is the builder for creating a RefinementTurn entity.
type RefinementTurnCreate struct {
	config
	mutation *RefinementTurnMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *RefinementTurnCreate) SetTaskID(v string) *RefinementTurnCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *RefinementTurnCreate) SetRole(v string) *RefinementTurnCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *RefinementTurnCreate) SetContent(v string) *RefinementTurnCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetPhase sets the "phase" field.
func (_c *RefinementTurnCreate) SetPhase(v string) *RefinementTurnCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *RefinementTurnCreate) SetNillablePhase(v *string) *RefinementTurnCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RefinementTurnCreate) SetCreatedAt(v time.Time) *RefinementTurnCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RefinementTurnCreate) SetNillableCreatedAt(v *time.Time) *RefinementTurnCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RefinementTurnCreate) SetID(v string) *RefinementTurnCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RefinementTurnMutation object of the builder.
func (_c *RefinementTurnCreate) Mutation() *RefinementTurnMutation {
	return _c.mutation
}

// Save creates the RefinementTurn in the database.
func (_c *RefinementTurnCreate) Save(ctx context.Context) (*RefinementTurn, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RefinementTurnCreate) SaveX(ctx context.Context) *RefinementTurn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefinementTurnCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefinementTurnCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RefinementTurnCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := refinementturn.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RefinementTurnCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "RefinementTurn.task_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "RefinementTurn.role"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "RefinementTurn.content"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RefinementTurn.created_at"`)}
	}
	return nil
}

func (_c *RefinementTurnCreate) sqlSave(ctx context.Context) (*RefinementTurn, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RefinementTurn.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RefinementTurnCreate) createSpec() (*RefinementTurn, *sqlgraph.CreateSpec) {
	var (
		_node = &RefinementTurn{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(refinementturn.Table, sqlgraph.NewFieldSpec(refinementturn.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(refinementturn.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(refinementturn.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(refinementturn.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(refinementturn.FieldPhase, field.TypeString, value)
		_node.Phase = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(refinementturn.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RefinementTurnCreateBulk is the builder for creating many RefinementTurn entities in bulk.
type RefinementTurnCreateBulk struct {
	config
	err      error
	builders []*RefinementTurnCreate
}

// Save creates the RefinementTurn entities in the database.
func (_c *RefinementTurnCreateBulk) Save(ctx context.Context) ([]*RefinementTurn, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RefinementTurn, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefinementTurnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RefinementTurnCreateBulk) SaveX(ctx context.Context) []*RefinementTurn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefinementTurnCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefinementTurnCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
