// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/remoteregistration"
)

// RemoteRegistrationCreate is the builder for creating a RemoteRegistration entity.
type RemoteRegistrationCreate struct {
	config
	mutation *RemoteRegistrationMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *RemoteRegistrationCreate) SetUserID(v string) *RemoteRegistrationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *RemoteRegistrationCreate) SetURL(v string) *RemoteRegistrationCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RemoteRegistrationCreate) SetName(v string) *RemoteRegistrationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *RemoteRegistrationCreate) SetNillableName(v *string) *RemoteRegistrationCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetBearerKey sets the "bearer_key" field.
func (_c *RemoteRegistrationCreate) SetBearerKey(v string) *RemoteRegistrationCreate {
	_c.mutation.SetBearerKey(v)
	return _c
}

// SetNillableBearerKey sets the "bearer_key" field if the given value is not nil.
func (_c *RemoteRegistrationCreate) SetNillableBearerKey(v *string) *RemoteRegistrationCreate {
	if v != nil {
		_c.SetBearerKey(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RemoteRegistrationCreate) SetCreatedAt(v time.Time) *RemoteRegistrationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RemoteRegistrationCreate) SetNillableCreatedAt(v *time.Time) *RemoteRegistrationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RemoteRegistrationCreate) SetID(v string) *RemoteRegistrationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RemoteRegistrationMutation object of the builder.
func (_c *RemoteRegistrationCreate) Mutation() *RemoteRegistrationMutation {
	return _c.mutation
}

// Save creates the RemoteRegistration in the database.
func (_c *RemoteRegistrationCreate) Save(ctx context.Context) (*RemoteRegistration, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RemoteRegistrationCreate) SaveX(ctx context.Context) *RemoteRegistration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteRegistrationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteRegistrationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RemoteRegistrationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := remoteregistration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RemoteRegistrationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RemoteRegistration.user_id"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "RemoteRegistration.url"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RemoteRegistration.created_at"`)}
	}
	return nil
}

func (_c *RemoteRegistrationCreate) sqlSave(ctx context.Context) (*RemoteRegistration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RemoteRegistration.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RemoteRegistrationCreate) createSpec() (*RemoteRegistration, *sqlgraph.CreateSpec) {
	var (
		_node = &RemoteRegistration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(remoteregistration.Table, sqlgraph.NewFieldSpec(remoteregistration.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(remoteregistration.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(remoteregistration.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(remoteregistration.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.BearerKey(); ok {
		_spec.SetField(remoteregistration.FieldBearerKey, field.TypeString, value)
		_node.BearerKey = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(remoteregistration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RemoteRegistrationCreateBulk is the builder for creating many RemoteRegistration entities in bulk.
type RemoteRegistrationCreateBulk struct {
	config
	err      error
	builders []*RemoteRegistrationCreate
}

// Save creates the RemoteRegistration entities in the database.
func (_c *RemoteRegistrationCreateBulk) Save(ctx context.Context) ([]*RemoteRegistration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RemoteRegistration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RemoteRegistrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RemoteRegistrationCreateBulk) SaveX(ctx context.Context) []*RemoteRegistration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteRegistrationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteRegistrationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
