// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/agentcosttrend"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/apikey"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/auditevent"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/driftalert"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/evalmetricsnapshot"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionrequest"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/projectfolder"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/refinementturn"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/remoteregistration"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/schema"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/spawner"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/stagerun"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/systemprompt"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/task"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskdependency"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskpermission"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskschedule"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentcosttrendFields := schema.AgentCostTrend{}.Fields()
	_ = agentcosttrendFields
	// agentcosttrendDescRecordedAt is the schema descriptor for recorded_at field.
	agentcosttrendDescRecordedAt := agentcosttrendFields[6].Descriptor()
	// agentcosttrend.DefaultRecordedAt holds the default value on creation for the recorded_at field.
	agentcosttrend.DefaultRecordedAt = agentcosttrendDescRecordedAt.Default.(func() time.Time)
	// agentcosttrendDescCwd is the schema descriptor for cwd field.
	agentcosttrendDescCwd := agentcosttrendFields[7].Descriptor()
	// agentcosttrend.DefaultCwd holds the default value on creation for the cwd field.
	agentcosttrend.DefaultCwd = agentcosttrendDescCwd.Default.(string)
	// agentcosttrendDescProjectPath is the schema descriptor for project_path field.
	agentcosttrendDescProjectPath := agentcosttrendFields[8].Descriptor()
	// agentcosttrend.DefaultProjectPath holds the default value on creation for the project_path field.
	agentcosttrend.DefaultProjectPath = agentcosttrendDescProjectPath.Default.(string)
	// agentcosttrendDescProjectName is the schema descriptor for project_name field.
	agentcosttrendDescProjectName := agentcosttrendFields[9].Descriptor()
	// agentcosttrend.DefaultProjectName holds the default value on creation for the project_name field.
	agentcosttrend.DefaultProjectName = agentcosttrendDescProjectName.Default.(string)
	// agentcosttrendDescSourceMtime is the schema descriptor for source_mtime field.
	agentcosttrendDescSourceMtime := agentcosttrendFields[10].Descriptor()
	// agentcosttrend.DefaultSourceMtime holds the default value on creation for the source_mtime field.
	agentcosttrend.DefaultSourceMtime = agentcosttrendDescSourceMtime.Default.(int64)
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescScopes is the schema descriptor for scopes field.
	apikeyDescScopes := apikeyFields[3].Descriptor()
	// apikey.DefaultScopes holds the default value on creation for the scopes field.
	apikey.DefaultScopes = apikeyDescScopes.Default.([]string)
	// apikeyDescActive is the schema descriptor for active field.
	apikeyDescActive := apikeyFields[4].Descriptor()
	// apikey.DefaultActive holds the default value on creation for the active field.
	apikey.DefaultActive = apikeyDescActive.Default.(bool)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[5].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescTs is the schema descriptor for ts field.
	auditeventDescTs := auditeventFields[1].Descriptor()
	// auditevent.DefaultTs holds the default value on creation for the ts field.
	auditevent.DefaultTs = auditeventDescTs.Default.(func() time.Time)
	driftalertFields := schema.DriftAlert{}.Fields()
	_ = driftalertFields
	// driftalertDescStatus is the schema descriptor for status field.
	driftalertDescStatus := driftalertFields[5].Descriptor()
	// driftalert.DefaultStatus holds the default value on creation for the status field.
	driftalert.DefaultStatus = driftalertDescStatus.Default.(string)
	// driftalertDescDetectedAt is the schema descriptor for detected_at field.
	driftalertDescDetectedAt := driftalertFields[12].Descriptor()
	// driftalert.DefaultDetectedAt holds the default value on creation for the detected_at field.
	driftalert.DefaultDetectedAt = driftalertDescDetectedAt.Default.(func() time.Time)
	evalmetricsnapshotFields := schema.EvalMetricSnapshot{}.Fields()
	_ = evalmetricsnapshotFields
	// evalmetricsnapshotDescRecordedAt is the schema descriptor for recorded_at field.
	evalmetricsnapshotDescRecordedAt := evalmetricsnapshotFields[9].Descriptor()
	// evalmetricsnapshot.DefaultRecordedAt holds the default value on creation for the recorded_at field.
	evalmetricsnapshot.DefaultRecordedAt = evalmetricsnapshotDescRecordedAt.Default.(func() time.Time)
	permissionrequestFields := schema.PermissionRequest{}.Fields()
	_ = permissionrequestFields
	// permissionrequestDescRequestedAt is the schema descriptor for requested_at field.
	permissionrequestDescRequestedAt := permissionrequestFields[6].Descriptor()
	// permissionrequest.DefaultRequestedAt holds the default value on creation for the requested_at field.
	permissionrequest.DefaultRequestedAt = permissionrequestDescRequestedAt.Default.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[6].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[7].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	projectfolderFields := schema.ProjectFolder{}.Fields()
	_ = projectfolderFields
	// projectfolderDescPath is the schema descriptor for path field.
	projectfolderDescPath := projectfolderFields[1].Descriptor()
	// projectfolder.PathValidator is a validator for the "path" field. It is called by the builders before save.
	projectfolder.PathValidator = projectfolderDescPath.Validators[0].(func(string) error)
	// projectfolderDescIsDefault is the schema descriptor for is_default field.
	projectfolderDescIsDefault := projectfolderFields[3].Descriptor()
	// projectfolder.DefaultIsDefault holds the default value on creation for the is_default field.
	projectfolder.DefaultIsDefault = projectfolderDescIsDefault.Default.(bool)
	// projectfolderDescCreatedAt is the schema descriptor for created_at field.
	projectfolderDescCreatedAt := projectfolderFields[4].Descriptor()
	// projectfolder.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectfolder.DefaultCreatedAt = projectfolderDescCreatedAt.Default.(func() time.Time)
	refinementturnFields := schema.RefinementTurn{}.Fields()
	_ = refinementturnFields
	// refinementturnDescCreatedAt is the schema descriptor for created_at field.
	refinementturnDescCreatedAt := refinementturnFields[5].Descriptor()
	// refinementturn.DefaultCreatedAt holds the default value on creation for the created_at field.
	refinementturn.DefaultCreatedAt = refinementturnDescCreatedAt.Default.(func() time.Time)
	remoteregistrationFields := schema.RemoteRegistration{}.Fields()
	_ = remoteregistrationFields
	// remoteregistrationDescCreatedAt is the schema descriptor for created_at field.
	remoteregistrationDescCreatedAt := remoteregistrationFields[5].Descriptor()
	// remoteregistration.DefaultCreatedAt holds the default value on creation for the created_at field.
	remoteregistration.DefaultCreatedAt = remoteregistrationDescCreatedAt.Default.(func() time.Time)
	spawnerFields := schema.Spawner{}.Fields()
	_ = spawnerFields
	// spawnerDescArgs is the schema descriptor for args field.
	spawnerDescArgs := spawnerFields[4].Descriptor()
	// spawner.DefaultArgs holds the default value on creation for the args field.
	spawner.DefaultArgs = spawnerDescArgs.Default.([]string)
	// spawnerDescEnv is the schema descriptor for env field.
	spawnerDescEnv := spawnerFields[5].Descriptor()
	// spawner.DefaultEnv holds the default value on creation for the env field.
	spawner.DefaultEnv = spawnerDescEnv.Default.(map[string]string)
	// spawnerDescAdapterType is the schema descriptor for adapter_type field.
	spawnerDescAdapterType := spawnerFields[6].Descriptor()
	// spawner.DefaultAdapterType holds the default value on creation for the adapter_type field.
	spawner.DefaultAdapterType = spawnerDescAdapterType.Default.(string)
	// spawnerDescAdapterConfig is the schema descriptor for adapter_config field.
	spawnerDescAdapterConfig := spawnerFields[7].Descriptor()
	// spawner.DefaultAdapterConfig holds the default value on creation for the adapter_config field.
	spawner.DefaultAdapterConfig = spawnerDescAdapterConfig.Default.(map[string]string)
	// spawnerDescBuiltIn is the schema descriptor for built_in field.
	spawnerDescBuiltIn := spawnerFields[10].Descriptor()
	// spawner.DefaultBuiltIn holds the default value on creation for the built_in field.
	spawner.DefaultBuiltIn = spawnerDescBuiltIn.Default.(bool)
	// spawnerDescIsDefault is the schema descriptor for is_default field.
	spawnerDescIsDefault := spawnerFields[11].Descriptor()
	// spawner.DefaultIsDefault holds the default value on creation for the is_default field.
	spawner.DefaultIsDefault = spawnerDescIsDefault.Default.(bool)
	// spawnerDescCreatedAt is the schema descriptor for created_at field.
	spawnerDescCreatedAt := spawnerFields[12].Descriptor()
	// spawner.DefaultCreatedAt holds the default value on creation for the created_at field.
	spawner.DefaultCreatedAt = spawnerDescCreatedAt.Default.(func() time.Time)
	// spawnerDescUpdatedAt is the schema descriptor for updated_at field.
	spawnerDescUpdatedAt := spawnerFields[13].Descriptor()
	// spawner.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	spawner.DefaultUpdatedAt = spawnerDescUpdatedAt.Default.(func() time.Time)
	// spawner.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	spawner.UpdateDefaultUpdatedAt = spawnerDescUpdatedAt.UpdateDefault.(func() time.Time)
	stagerunFields := schema.StageRun{}.Fields()
	_ = stagerunFields
	// stagerunDescStatus is the schema descriptor for status field.
	stagerunDescStatus := stagerunFields[6].Descriptor()
	// stagerun.DefaultStatus holds the default value on creation for the status field.
	stagerun.DefaultStatus = stagerunDescStatus.Default.(string)
	// stagerunDescIteration is the schema descriptor for iteration field.
	stagerunDescIteration := stagerunFields[7].Descriptor()
	// stagerun.DefaultIteration holds the default value on creation for the iteration field.
	stagerun.DefaultIteration = stagerunDescIteration.Default.(int)
	// stagerunDescTokensUsed is the schema descriptor for tokens_used field.
	stagerunDescTokensUsed := stagerunFields[9].Descriptor()
	// stagerun.DefaultTokensUsed holds the default value on creation for the tokens_used field.
	stagerun.DefaultTokensUsed = stagerunDescTokensUsed.Default.(int)
	// stagerunDescCostCents is the schema descriptor for cost_cents field.
	stagerunDescCostCents := stagerunFields[10].Descriptor()
	// stagerun.DefaultCostCents holds the default value on creation for the cost_cents field.
	stagerun.DefaultCostCents = stagerunDescCostCents.Default.(int)
	// stagerunDescRetryCount is the schema descriptor for retry_count field.
	stagerunDescRetryCount := stagerunFields[14].Descriptor()
	// stagerun.DefaultRetryCount holds the default value on creation for the retry_count field.
	stagerun.DefaultRetryCount = stagerunDescRetryCount.Default.(int)
	// stagerunDescCreatedAt is the schema descriptor for created_at field.
	stagerunDescCreatedAt := stagerunFields[17].Descriptor()
	// stagerun.DefaultCreatedAt holds the default value on creation for the created_at field.
	stagerun.DefaultCreatedAt = stagerunDescCreatedAt.Default.(func() time.Time)
	systempromptFields := schema.SystemPrompt{}.Fields()
	_ = systempromptFields
	// systempromptDescScope is the schema descriptor for scope field.
	systempromptDescScope := systempromptFields[1].Descriptor()
	// systemprompt.DefaultScope holds the default value on creation for the scope field.
	systemprompt.DefaultScope = systempromptDescScope.Default.(string)
	// systempromptDescPriority is the schema descriptor for priority field.
	systempromptDescPriority := systempromptFields[4].Descriptor()
	// systemprompt.DefaultPriority holds the default value on creation for the priority field.
	systemprompt.DefaultPriority = systempromptDescPriority.Default.(int)
	// systempromptDescCreatedAt is the schema descriptor for created_at field.
	systempromptDescCreatedAt := systempromptFields[6].Descriptor()
	// systemprompt.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemprompt.DefaultCreatedAt = systempromptDescCreatedAt.Default.(func() time.Time)
	// systempromptDescUpdatedAt is the schema descriptor for updated_at field.
	systempromptDescUpdatedAt := systempromptFields[7].Descriptor()
	// systemprompt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemprompt.DefaultUpdatedAt = systempromptDescUpdatedAt.Default.(func() time.Time)
	// systemprompt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemprompt.UpdateDefaultUpdatedAt = systempromptDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[2].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = taskDescTitle.Validators[0].(func(string) error)
	// taskDescCwd is the schema descriptor for cwd field.
	taskDescCwd := taskFields[4].Descriptor()
	// task.CwdValidator is a validator for the "cwd" field. It is called by the builders before save.
	task.CwdValidator = taskDescCwd.Validators[0].(func(string) error)
	// taskDescCurrentStage is the schema descriptor for current_stage field.
	taskDescCurrentStage := taskFields[8].Descriptor()
	// task.DefaultCurrentStage holds the default value on creation for the current_stage field.
	task.DefaultCurrentStage = taskDescCurrentStage.Default.(string)
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[9].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(string)
	// taskDescMaxIterations is the schema descriptor for max_iterations field.
	taskDescMaxIterations := taskFields[12].Descriptor()
	// task.DefaultMaxIterations holds the default value on creation for the max_iterations field.
	task.DefaultMaxIterations = taskDescMaxIterations.Default.(int)
	// taskDescStageTimeoutSeconds is the schema descriptor for stage_timeout_seconds field.
	taskDescStageTimeoutSeconds := taskFields[15].Descriptor()
	// task.DefaultStageTimeoutSeconds holds the default value on creation for the stage_timeout_seconds field.
	task.DefaultStageTimeoutSeconds = taskDescStageTimeoutSeconds.Default.(int)
	// taskDescSilverBullet is the schema descriptor for silver_bullet field.
	taskDescSilverBullet := taskFields[16].Descriptor()
	// task.DefaultSilverBullet holds the default value on creation for the silver_bullet field.
	task.DefaultSilverBullet = taskDescSilverBullet.Default.(bool)
	// taskDescAutonomy is the schema descriptor for autonomy field.
	taskDescAutonomy := taskFields[17].Descriptor()
	// task.DefaultAutonomy holds the default value on creation for the autonomy field.
	task.DefaultAutonomy = taskDescAutonomy.Default.(string)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[22].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[23].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskdependencyFields := schema.TaskDependency{}.Fields()
	_ = taskdependencyFields
	// taskdependencyDescRequiredStage is the schema descriptor for required_stage field.
	taskdependencyDescRequiredStage := taskdependencyFields[3].Descriptor()
	// taskdependency.DefaultRequiredStage holds the default value on creation for the required_stage field.
	taskdependency.DefaultRequiredStage = taskdependencyDescRequiredStage.Default.(string)
	// taskdependencyDescOnCancelAction is the schema descriptor for on_cancel_action field.
	taskdependencyDescOnCancelAction := taskdependencyFields[4].Descriptor()
	// taskdependency.DefaultOnCancelAction holds the default value on creation for the on_cancel_action field.
	taskdependency.DefaultOnCancelAction = taskdependencyDescOnCancelAction.Default.(string)
	taskpermissionFields := schema.TaskPermission{}.Fields()
	_ = taskpermissionFields
	// taskpermissionDescGranted is the schema descriptor for granted field.
	taskpermissionDescGranted := taskpermissionFields[4].Descriptor()
	// taskpermission.DefaultGranted holds the default value on creation for the granted field.
	taskpermission.DefaultGranted = taskpermissionDescGranted.Default.(bool)
	// taskpermissionDescPreApproved is the schema descriptor for pre_approved field.
	taskpermissionDescPreApproved := taskpermissionFields[5].Descriptor()
	// taskpermission.DefaultPreApproved holds the default value on creation for the pre_approved field.
	taskpermission.DefaultPreApproved = taskpermissionDescPreApproved.Default.(bool)
	// taskpermissionDescManualOverride is the schema descriptor for manual_override field.
	taskpermissionDescManualOverride := taskpermissionFields[6].Descriptor()
	// taskpermission.DefaultManualOverride holds the default value on creation for the manual_override field.
	taskpermission.DefaultManualOverride = taskpermissionDescManualOverride.Default.(bool)
	// taskpermissionDescRequestedAt is the schema descriptor for requested_at field.
	taskpermissionDescRequestedAt := taskpermissionFields[8].Descriptor()
	// taskpermission.DefaultRequestedAt holds the default value on creation for the requested_at field.
	taskpermission.DefaultRequestedAt = taskpermissionDescRequestedAt.Default.(func() time.Time)
	taskscheduleFields := schema.TaskSchedule{}.Fields()
	_ = taskscheduleFields
	// taskscheduleDescName is the schema descriptor for name field.
	taskscheduleDescName := taskscheduleFields[1].Descriptor()
	// taskschedule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	taskschedule.NameValidator = taskscheduleDescName.Validators[0].(func(string) error)
	// taskscheduleDescEnabled is the schema descriptor for enabled field.
	taskscheduleDescEnabled := taskscheduleFields[2].Descriptor()
	// taskschedule.DefaultEnabled holds the default value on creation for the enabled field.
	taskschedule.DefaultEnabled = taskscheduleDescEnabled.Default.(bool)
	// taskscheduleDescTimezone is the schema descriptor for timezone field.
	taskscheduleDescTimezone := taskscheduleFields[5].Descriptor()
	// taskschedule.DefaultTimezone holds the default value on creation for the timezone field.
	taskschedule.DefaultTimezone = taskscheduleDescTimezone.Default.(string)
	// taskscheduleDescCatchup is the schema descriptor for catchup field.
	taskscheduleDescCatchup := taskscheduleFields[6].Descriptor()
	// taskschedule.DefaultCatchup holds the default value on creation for the catchup field.
	taskschedule.DefaultCatchup = taskscheduleDescCatchup.Default.(string)
	// taskscheduleDescSlugPrefix is the schema descriptor for slug_prefix field.
	taskscheduleDescSlugPrefix := taskscheduleFields[7].Descriptor()
	// taskschedule.SlugPrefixValidator is a validator for the "slug_prefix" field. It is called by the builders before save.
	taskschedule.SlugPrefixValidator = taskscheduleDescSlugPrefix.Validators[0].(func(string) error)
	// taskscheduleDescTitle is the schema descriptor for title field.
	taskscheduleDescTitle := taskscheduleFields[8].Descriptor()
	// taskschedule.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	taskschedule.TitleValidator = taskscheduleDescTitle.Validators[0].(func(string) error)
	// taskscheduleDescCwd is the schema descriptor for cwd field.
	taskscheduleDescCwd := taskscheduleFields[10].Descriptor()
	// taskschedule.CwdValidator is a validator for the "cwd" field. It is called by the builders before save.
	taskschedule.CwdValidator = taskscheduleDescCwd.Validators[0].(func(string) error)
	// taskscheduleDescPriority is the schema descriptor for priority field.
	taskscheduleDescPriority := taskscheduleFields[13].Descriptor()
	// taskschedule.DefaultPriority holds the default value on creation for the priority field.
	taskschedule.DefaultPriority = taskscheduleDescPriority.Default.(string)
	// taskscheduleDescCurrentStage is the schema descriptor for current_stage field.
	taskscheduleDescCurrentStage := taskscheduleFields[14].Descriptor()
	// taskschedule.DefaultCurrentStage holds the default value on creation for the current_stage field.
	taskschedule.DefaultCurrentStage = taskscheduleDescCurrentStage.Default.(string)
	// taskscheduleDescMaxIterations is the schema descriptor for max_iterations field.
	taskscheduleDescMaxIterations := taskscheduleFields[15].Descriptor()
	// taskschedule.DefaultMaxIterations holds the default value on creation for the max_iterations field.
	taskschedule.DefaultMaxIterations = taskscheduleDescMaxIterations.Default.(int)
	// taskscheduleDescStageTimeoutSeconds is the schema descriptor for stage_timeout_seconds field.
	taskscheduleDescStageTimeoutSeconds := taskscheduleFields[18].Descriptor()
	// taskschedule.DefaultStageTimeoutSeconds holds the default value on creation for the stage_timeout_seconds field.
	taskschedule.DefaultStageTimeoutSeconds = taskscheduleDescStageTimeoutSeconds.Default.(int)
	// taskscheduleDescSilverBullet is the schema descriptor for silver_bullet field.
	taskscheduleDescSilverBullet := taskscheduleFields[19].Descriptor()
	// taskschedule.DefaultSilverBullet holds the default value on creation for the silver_bullet field.
	taskschedule.DefaultSilverBullet = taskscheduleDescSilverBullet.Default.(bool)
	// taskscheduleDescCreatedAt is the schema descriptor for created_at field.
	taskscheduleDescCreatedAt := taskscheduleFields[28].Descriptor()
	// taskschedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	taskschedule.DefaultCreatedAt = taskscheduleDescCreatedAt.Default.(func() time.Time)
	// taskscheduleDescUpdatedAt is the schema descriptor for updated_at field.
	taskscheduleDescUpdatedAt := taskscheduleFields[29].Descriptor()
	// taskschedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	taskschedule.DefaultUpdatedAt = taskscheduleDescUpdatedAt.Default.(func() time.Time)
	// taskschedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	taskschedule.UpdateDefaultUpdatedAt = taskscheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[4].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
