// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/spawner"
)

// SpawnerCreate is the builder for creating a Spawner entity.
type SpawnerCreate struct {
	config
	mutation *SpawnerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SpawnerCreate) SetName(v string) *SpawnerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *SpawnerCreate) SetSlug(v string) *SpawnerCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetCommand sets the "command" field.
func (_c *SpawnerCreate) SetCommand(v string) *SpawnerCreate {
	_c.mutation.SetCommand(v)
	return _c
}

// SetArgs sets the "args" field.
func (_c *SpawnerCreate) SetArgs(v []string) *SpawnerCreate {
	_c.mutation.SetArgs(v)
	return _c
}

// SetEnv sets the "env" field.
func (_c *SpawnerCreate) SetEnv(v map[string]string) *SpawnerCreate {
	_c.mutation.SetEnv(v)
	return _c
}

// SetAdapterType sets the "adapter_type" field.
func (_c *SpawnerCreate) SetAdapterType(v string) *SpawnerCreate {
	_c.mutation.SetAdapterType(v)
	return _c
}

// SetNillableAdapterType sets the "adapter_type" field if the given value is not nil.
func (_c *SpawnerCreate) SetNillableAdapterType(v *string) *SpawnerCreate {
	if v != nil {
		_c.SetAdapterType(*v)
	}
	return _c
}

// SetAdapterConfig sets the "adapter_config" field.
func (_c *SpawnerCreate) SetAdapterConfig(v map[string]string) *SpawnerCreate {
	_c.mutation.SetAdapterConfig(v)
	return _c
}

// SetModelOverride sets the "model_override" field.
func (_c *SpawnerCreate) SetModelOverride(v string) *SpawnerCreate {
	_c.mutation.SetModelOverride(v)
	return _c
}

// SetNillableModelOverride sets the "model_override" field if the given value is not nil.
func (_c *SpawnerCreate) SetNillableModelOverride(v *string) *SpawnerCreate {
	if v != nil {
		_c.SetModelOverride(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SpawnerCreate) SetDescription(v string) *SpawnerCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SpawnerCreate) SetNillableDescription(v *string) *SpawnerCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetBuiltIn sets the "built_in" field.
func (_c *SpawnerCreate) SetBuiltIn(v bool) *SpawnerCreate {
	_c.mutation.SetBuiltIn(v)
	return _c
}

// SetNillableBuiltIn sets the "built_in" field if the given value is not nil.
func (_c *SpawnerCreate) SetNillableBuiltIn(v *bool) *SpawnerCreate {
	if v != nil {
		_c.SetBuiltIn(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SpawnerCreate) SetCreatedAt(v time.Time) *SpawnerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SpawnerCreate) SetNillableCreatedAt(v *time.Time) *SpawnerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SpawnerCreate) SetUpdatedAt(v time.Time) *SpawnerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SpawnerCreate) SetNillableUpdatedAt(v *time.Time) *SpawnerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SpawnerCreate) SetID(v string) *SpawnerCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SpawnerMutation object of the builder.
func (_c *SpawnerCreate) Mutation() *SpawnerMutation {
	return _c.mutation
}

// Save creates the Spawner in the database.
func (_c *SpawnerCreate) Save(ctx context.Context) (*Spawner, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SpawnerCreate) SaveX(ctx context.Context) *Spawner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SpawnerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SpawnerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SpawnerCreate) defaults() {
	if _, ok := _c.mutation.Args(); !ok {
		v := spawner.DefaultArgs
		_c.mutation.SetArgs(v)
	}
	if _, ok := _c.mutation.Env(); !ok {
		v := spawner.DefaultEnv
		_c.mutation.SetEnv(v)
	}
	if _, ok := _c.mutation.AdapterType(); !ok {
		v := spawner.DefaultAdapterType
		_c.mutation.SetAdapterType(v)
	}
	if _, ok := _c.mutation.AdapterConfig(); !ok {
		v := spawner.DefaultAdapterConfig
		_c.mutation.SetAdapterConfig(v)
	}
	if _, ok := _c.mutation.BuiltIn(); !ok {
		v := spawner.DefaultBuiltIn
		_c.mutation.SetBuiltIn(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := spawner.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := spawner.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SpawnerCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Spawner.name"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Spawner.slug"`)}
	}
	if _, ok := _c.mutation.Command(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required field "Spawner.command"`)}
	}
	if _, ok := _c.mutation.Args(); !ok {
		return &ValidationError{Name: "args", err: errors.New(`ent: missing required field "Spawner.args"`)}
	}
	if _, ok := _c.mutation.Env(); !ok {
		return &ValidationError{Name: "env", err: errors.New(`ent: missing required field "Spawner.env"`)}
	}
	if _, ok := _c.mutation.AdapterType(); !ok {
		return &ValidationError{Name: "adapter_type", err: errors.New(`ent: missing required field "Spawner.adapter_type"`)}
	}
	if _, ok := _c.mutation.AdapterConfig(); !ok {
		return &ValidationError{Name: "adapter_config", err: errors.New(`ent: missing required field "Spawner.adapter_config"`)}
	}
	if _, ok := _c.mutation.BuiltIn(); !ok {
		return &ValidationError{Name: "built_in", err: errors.New(`ent: missing required field "Spawner.built_in"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Spawner.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Spawner.updated_at"`)}
	}
	return nil
}

func (_c *SpawnerCreate) sqlSave(ctx context.Context) (*Spawner, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Spawner.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SpawnerCreate) createSpec() (*Spawner, *sqlgraph.CreateSpec) {
	var (
		_node = &Spawner{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(spawner.Table, sqlgraph.NewFieldSpec(spawner.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(spawner.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(spawner.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Command(); ok {
		_spec.SetField(spawner.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := _c.mutation.Args(); ok {
		_spec.SetField(spawner.FieldArgs, field.TypeJSON, value)
		_node.Args = value
	}
	if value, ok := _c.mutation.Env(); ok {
		_spec.SetField(spawner.FieldEnv, field.TypeJSON, value)
		_node.Env = value
	}
	if value, ok := _c.mutation.AdapterType(); ok {
		_spec.SetField(spawner.FieldAdapterType, field.TypeString, value)
		_node.AdapterType = value
	}
	if value, ok := _c.mutation.AdapterConfig(); ok {
		_spec.SetField(spawner.FieldAdapterConfig, field.TypeJSON, value)
		_node.AdapterConfig = value
	}
	if value, ok := _c.mutation.ModelOverride(); ok {
		_spec.SetField(spawner.FieldModelOverride, field.TypeString, value)
		_node.ModelOverride = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(spawner.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.BuiltIn(); ok {
		_spec.SetField(spawner.FieldBuiltIn, field.TypeBool, value)
		_node.BuiltIn = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(spawner.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(spawner.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SpawnerCreateBulk is the builder for creating many Spawner entities in bulk.
type SpawnerCreateBulk struct {
	config
	err      error
	builders []*SpawnerCreate
}

// Save creates the Spawner entities in the database.
func (_c *SpawnerCreateBulk) Save(ctx context.Context) ([]*Spawner, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Spawner, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpawnerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SpawnerCreateBulk) SaveX(ctx context.Context) []*Spawner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SpawnerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SpawnerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
