// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionrequest"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/stagerun"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/task"
)

// StageRunCreate is the builder for creating a StageRun entity.
type StageRunCreate struct {
	config
	mutation *StageRunMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *StageRunCreate) SetTaskID(v string) *StageRunCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetStage sets the "stage" field.
func (_c *StageRunCreate) SetStage(v string) *StageRunCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *StageRunCreate) SetSessionID(v string) *StageRunCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableSessionID(v *string) *StageRunCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetSessionName sets the "session_name" field.
func (_c *StageRunCreate) SetSessionName(v string) *StageRunCreate {
	_c.mutation.SetSessionName(v)
	return _c
}

// SetNillableSessionName sets the "session_name" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableSessionName(v *string) *StageRunCreate {
	if v != nil {
		_c.SetSessionName(*v)
	}
	return _c
}

// SetPid sets the "pid" field.
func (_c *StageRunCreate) SetPid(v int) *StageRunCreate {
	_c.mutation.SetPid(v)
	return _c
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_c *StageRunCreate) SetNillablePid(v *int) *StageRunCreate {
	if v != nil {
		_c.SetPid(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StageRunCreate) SetStatus(v string) *StageRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableStatus(v *string) *StageRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIteration sets the "iteration" field.
func (_c *StageRunCreate) SetIteration(v int) *StageRunCreate {
	_c.mutation.SetIteration(v)
	return _c
}

// SetNillableIteration sets the "iteration" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableIteration(v *int) *StageRunCreate {
	if v != nil {
		_c.SetIteration(*v)
	}
	return _c
}

// SetOutput sets the "output" field.
func (_c *StageRunCreate) SetOutput(v map[string]interface{}) *StageRunCreate {
	_c.mutation.SetOutput(v)
	return _c
}

// SetTokensUsed sets the "tokens_used" field.
func (_c *StageRunCreate) SetTokensUsed(v int) *StageRunCreate {
	_c.mutation.SetTokensUsed(v)
	return _c
}

// SetNillableTokensUsed sets the "tokens_used" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableTokensUsed(v *int) *StageRunCreate {
	if v != nil {
		_c.SetTokensUsed(*v)
	}
	return _c
}

// SetCostCents sets the "cost_cents" field.
func (_c *StageRunCreate) SetCostCents(v int) *StageRunCreate {
	_c.mutation.SetCostCents(v)
	return _c
}

// SetNillableCostCents sets the "cost_cents" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableCostCents(v *int) *StageRunCreate {
	if v != nil {
		_c.SetCostCents(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *StageRunCreate) SetStartedAt(v time.Time) *StageRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableStartedAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *StageRunCreate) SetEndedAt(v time.Time) *StageRunCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableEndedAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetLastGrantAt sets the "last_grant_at" field.
func (_c *StageRunCreate) SetLastGrantAt(v time.Time) *StageRunCreate {
	_c.mutation.SetLastGrantAt(v)
	return _c
}

// SetNillableLastGrantAt sets the "last_grant_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableLastGrantAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetLastGrantAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StageRunCreate) SetCreatedAt(v time.Time) *StageRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableCreatedAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StageRunCreate) SetID(v string) *StageRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *StageRunCreate) SetTask(v *Task) *StageRunCreate {
	return _c.SetTaskID(v.ID)
}

// AddPermissionRequestIDs adds the "permission_requests" edge to the PermissionRequest entity by IDs.
func (_c *StageRunCreate) AddPermissionRequestIDs(ids ...string) *StageRunCreate {
	_c.mutation.AddPermissionRequestIDs(ids...)
	return _c
}

// AddPermissionRequests adds the "permission_requests" edges to the PermissionRequest entity.
func (_c *StageRunCreate) AddPermissionRequests(v ...*PermissionRequest) *StageRunCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionRequestIDs(ids...)
}

// Mutation returns the StageRunMutation object of the builder.
func (_c *StageRunCreate) Mutation() *StageRunMutation {
	return _c.mutation
}

// Save creates the StageRun in the database.
func (_c *StageRunCreate) Save(ctx context.Context) (*StageRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StageRunCreate) SaveX(ctx context.Context) *StageRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StageRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StageRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StageRunCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := stagerun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Iteration(); !ok {
		v := stagerun.DefaultIteration
		_c.mutation.SetIteration(v)
	}
	if _, ok := _c.mutation.TokensUsed(); !ok {
		v := stagerun.DefaultTokensUsed
		_c.mutation.SetTokensUsed(v)
	}
	if _, ok := _c.mutation.CostCents(); !ok {
		v := stagerun.DefaultCostCents
		_c.mutation.SetCostCents(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := stagerun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StageRunCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "StageRun.task_id"`)}
	}
	if _, ok := _c.mutation.Stage(); !ok {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required field "StageRun.stage"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StageRun.status"`)}
	}
	if _, ok := _c.mutation.Iteration(); !ok {
		return &ValidationError{Name: "iteration", err: errors.New(`ent: missing required field "StageRun.iteration"`)}
	}
	if _, ok := _c.mutation.TokensUsed(); !ok {
		return &ValidationError{Name: "tokens_used", err: errors.New(`ent: missing required field "StageRun.tokens_used"`)}
	}
	if _, ok := _c.mutation.CostCents(); !ok {
		return &ValidationError{Name: "cost_cents", err: errors.New(`ent: missing required field "StageRun.cost_cents"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StageRun.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "StageRun.task"`)}
	}
	return nil
}

func (_c *StageRunCreate) sqlSave(ctx context.Context) (*StageRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected StageRun.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StageRunCreate) createSpec() (*StageRun, *sqlgraph.CreateSpec) {
	var (
		_node = &StageRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(stagerun.Table, sqlgraph.NewFieldSpec(stagerun.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(stagerun.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(stagerun.FieldSessionID, field.TypeString, value)
		_node.SessionID = &value
	}
	if value, ok := _c.mutation.SessionName(); ok {
		_spec.SetField(stagerun.FieldSessionName, field.TypeString, value)
		_node.SessionName = &value
	}
	if value, ok := _c.mutation.Pid(); ok {
		_spec.SetField(stagerun.FieldPid, field.TypeInt, value)
		_node.Pid = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(stagerun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Iteration(); ok {
		_spec.SetField(stagerun.FieldIteration, field.TypeInt, value)
		_node.Iteration = value
	}
	if value, ok := _c.mutation.Output(); ok {
		_spec.SetField(stagerun.FieldOutput, field.TypeJSON, value)
		_node.Output = value
	}
	if value, ok := _c.mutation.TokensUsed(); ok {
		_spec.SetField(stagerun.FieldTokensUsed, field.TypeInt, value)
		_node.TokensUsed = value
	}
	if value, ok := _c.mutation.CostCents(); ok {
		_spec.SetField(stagerun.FieldCostCents, field.TypeInt, value)
		_node.CostCents = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(stagerun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(stagerun.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.LastGrantAt(); ok {
		_spec.SetField(stagerun.FieldLastGrantAt, field.TypeTime, value)
		_node.LastGrantAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(stagerun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stagerun.TaskTable,
			Columns: []string{stagerun.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stagerun.PermissionRequestsTable,
			Columns: []string{stagerun.PermissionRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionrequest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StageRunCreateBulk is the builder for creating many StageRun entities in bulk.
type StageRunCreateBulk struct {
	config
	err      error
	builders []*StageRunCreate
}

// Save creates the StageRun entities in the database.
func (_c *StageRunCreateBulk) Save(ctx context.Context) ([]*StageRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StageRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StageRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StageRunCreateBulk) SaveX(ctx context.Context) []*StageRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StageRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StageRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
