// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/systemprompt"
)

// SystemPromptCreate is the builder for creating a SystemPrompt entity.
type SystemPromptCreate struct {
	config
	mutation *SystemPromptMutation
	hooks    []Hook
}

// SetScope sets the "scope" field.
func (_c *SystemPromptCreate) SetScope(v string) *SystemPromptCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableScope(v *string) *SystemPromptCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetStage sets the "stage" field.
func (_c *SystemPromptCreate) SetStage(v string) *SystemPromptCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableStage(v *string) *SystemPromptCreate {
	if v != nil {
		_c.SetStage(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *SystemPromptCreate) SetContent(v string) *SystemPromptCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SystemPromptCreate) SetPriority(v int) *SystemPromptCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillablePriority(v *int) *SystemPromptCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SystemPromptCreate) SetCreatedBy(v string) *SystemPromptCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableCreatedBy(v *string) *SystemPromptCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemPromptCreate) SetCreatedAt(v time.Time) *SystemPromptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableCreatedAt(v *time.Time) *SystemPromptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SystemPromptCreate) SetUpdatedAt(v time.Time) *SystemPromptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableUpdatedAt(v *time.Time) *SystemPromptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SystemPromptCreate) SetID(v string) *SystemPromptCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SystemPromptMutation object of the builder.
func (_c *SystemPromptCreate) Mutation() *SystemPromptMutation {
	return _c.mutation
}

// Save creates the SystemPrompt in the database.
func (_c *SystemPromptCreate) Save(ctx context.Context) (*SystemPrompt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemPromptCreate) SaveX(ctx context.Context) *SystemPrompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemPromptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemPromptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemPromptCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := systemprompt.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := systemprompt.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := systemprompt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := systemprompt.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemPromptCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SystemPrompt.scope"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SystemPrompt.content"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SystemPrompt.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemPrompt.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemPrompt.updated_at"`)}
	}
	return nil
}

func (_c *SystemPromptCreate) sqlSave(ctx context.Context) (*SystemPrompt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SystemPrompt.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemPromptCreate) createSpec() (*SystemPrompt, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemPrompt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(systemprompt.Table, sqlgraph.NewFieldSpec(systemprompt.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(systemprompt.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(systemprompt.FieldStage, field.TypeString, value)
		_node.Stage = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(systemprompt.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(systemprompt.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(systemprompt.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(systemprompt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(systemprompt.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SystemPromptCreateBulk is the builder for creating many SystemPrompt entities in bulk.
type SystemPromptCreateBulk struct {
	config
	err      error
	builders []*SystemPromptCreate
}

// Save creates the SystemPrompt entities in the database.
func (_c *SystemPromptCreateBulk) Save(ctx context.Context) ([]*SystemPrompt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SystemPrompt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemPromptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemPromptCreateBulk) SaveX(ctx context.Context) []*SystemPrompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemPromptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemPromptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
