// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/stagerun"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/task"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskdependency"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskpermission"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (_c *TaskCreate) SetSlug(v string) *TaskCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *TaskCreate) SetTitle(v string) *TaskCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TaskCreate) SetDescription(v string) *TaskCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TaskCreate) SetNillableDescription(v *string) *TaskCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCwd sets the "cwd" field.
func (_c *TaskCreate) SetCwd(v string) *TaskCreate {
	_c.mutation.SetCwd(v)
	return _c
}

// SetWorktreePath sets the "worktree_path" field.
func (_c *TaskCreate) SetWorktreePath(v string) *TaskCreate {
	_c.mutation.SetWorktreePath(v)
	return _c
}

// SetNillableWorktreePath sets the "worktree_path" field if the given value is not nil.
func (_c *TaskCreate) SetNillableWorktreePath(v *string) *TaskCreate {
	if v != nil {
		_c.SetWorktreePath(*v)
	}
	return _c
}

// SetSourceBranch sets the "source_branch" field.
func (_c *TaskCreate) SetSourceBranch(v string) *TaskCreate {
	_c.mutation.SetSourceBranch(v)
	return _c
}

// SetNillableSourceBranch sets the "source_branch" field if the given value is not nil.
func (_c *TaskCreate) SetNillableSourceBranch(v *string) *TaskCreate {
	if v != nil {
		_c.SetSourceBranch(*v)
	}
	return _c
}

// SetTargetBranch sets the "target_branch" field.
func (_c *TaskCreate) SetTargetBranch(v string) *TaskCreate {
	_c.mutation.SetTargetBranch(v)
	return _c
}

// SetNillableTargetBranch sets the "target_branch" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTargetBranch(v *string) *TaskCreate {
	if v != nil {
		_c.SetTargetBranch(*v)
	}
	return _c
}

// SetCurrentStage sets the "current_stage" field.
func (_c *TaskCreate) SetCurrentStage(v string) *TaskCreate {
	_c.mutation.SetCurrentStage(v)
	return _c
}

// SetNillableCurrentStage sets the "current_stage" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCurrentStage(v *string) *TaskCreate {
	if v != nil {
		_c.SetCurrentStage(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *TaskCreate) SetPriority(v string) *TaskCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *TaskCreate) SetNillablePriority(v *string) *TaskCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TaskCreate) SetUserID(v string) *TaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableUserID(v *string) *TaskCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetParentTaskID sets the "parent_task_id" field.
func (_c *TaskCreate) SetParentTaskID(v string) *TaskCreate {
	_c.mutation.SetParentTaskID(v)
	return _c
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableParentTaskID(v *string) *TaskCreate {
	if v != nil {
		_c.SetParentTaskID(*v)
	}
	return _c
}

// SetMaxIterations sets the "max_iterations" field.
func (_c *TaskCreate) SetMaxIterations(v int) *TaskCreate {
	_c.mutation.SetMaxIterations(v)
	return _c
}

// SetNillableMaxIterations sets the "max_iterations" field if the given value is not nil.
func (_c *TaskCreate) SetNillableMaxIterations(v *int) *TaskCreate {
	if v != nil {
		_c.SetMaxIterations(*v)
	}
	return _c
}

// SetTokenBudget sets the "token_budget" field.
func (_c *TaskCreate) SetTokenBudget(v int) *TaskCreate {
	_c.mutation.SetTokenBudget(v)
	return _c
}

// SetNillableTokenBudget sets the "token_budget" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTokenBudget(v *int) *TaskCreate {
	if v != nil {
		_c.SetTokenBudget(*v)
	}
	return _c
}

// SetCostBudgetCents sets the "cost_budget_cents" field.
func (_c *TaskCreate) SetCostBudgetCents(v int) *TaskCreate {
	_c.mutation.SetCostBudgetCents(v)
	return _c
}

// SetNillableCostBudgetCents sets the "cost_budget_cents" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCostBudgetCents(v *int) *TaskCreate {
	if v != nil {
		_c.SetCostBudgetCents(*v)
	}
	return _c
}

// SetStageTimeoutSeconds sets the "stage_timeout_seconds" field.
func (_c *TaskCreate) SetStageTimeoutSeconds(v int) *TaskCreate {
	_c.mutation.SetStageTimeoutSeconds(v)
	return _c
}

// SetNillableStageTimeoutSeconds sets the "stage_timeout_seconds" field if the given value is not nil.
func (_c *TaskCreate) SetNillableStageTimeoutSeconds(v *int) *TaskCreate {
	if v != nil {
		_c.SetStageTimeoutSeconds(*v)
	}
	return _c
}

// SetSilverBullet sets the "silver_bullet" field.
func (_c *TaskCreate) SetSilverBullet(v bool) *TaskCreate {
	_c.mutation.SetSilverBullet(v)
	return _c
}

// SetNillableSilverBullet sets the "silver_bullet" field if the given value is not nil.
func (_c *TaskCreate) SetNillableSilverBullet(v *bool) *TaskCreate {
	if v != nil {
		_c.SetSilverBullet(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *TaskCreate) SetMetadata(v map[string]interface{}) *TaskCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *TaskCreate) SetProjectID(v string) *TaskCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableProjectID(v *string) *TaskCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetSpawnerID sets the "spawner_id" field.
func (_c *TaskCreate) SetSpawnerID(v string) *TaskCreate {
	_c.mutation.SetSpawnerID(v)
	return _c
}

// SetNillableSpawnerID sets the "spawner_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableSpawnerID(v *string) *TaskCreate {
	if v != nil {
		_c.SetSpawnerID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskCreate) SetCreatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCreatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskCreate) SetUpdatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableUpdatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskCreate) SetID(v string) *TaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddStageRunIDs adds the "stage_runs" edge to the StageRun entity by IDs.
func (_c *TaskCreate) AddStageRunIDs(ids ...string) *TaskCreate {
	_c.mutation.AddStageRunIDs(ids...)
	return _c
}

// AddStageRuns adds the "stage_runs" edges to the StageRun entity.
func (_c *TaskCreate) AddStageRuns(v ...*StageRun) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStageRunIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the TaskPermission entity by IDs.
func (_c *TaskCreate) AddPermissionIDs(ids ...string) *TaskCreate {
	_c.mutation.AddPermissionIDs(ids...)
	return _c
}

// AddPermissions adds the "permissions" edges to the TaskPermission entity.
func (_c *TaskCreate) AddPermissions(v ...*TaskPermission) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionIDs(ids...)
}

// AddDependencyIDs adds the "dependencies" edge to the TaskDependency entity by IDs.
func (_c *TaskCreate) AddDependencyIDs(ids ...string) *TaskCreate {
	_c.mutation.AddDependencyIDs(ids...)
	return _c
}

// AddDependencies adds the "dependencies" edges to the TaskDependency entity.
func (_c *TaskCreate) AddDependencies(v ...*TaskDependency) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDependencyIDs(ids...)
}

// AddDependentIDs adds the "dependents" edge to the TaskDependency entity by IDs.
func (_c *TaskCreate) AddDependentIDs(ids ...string) *TaskCreate {
	_c.mutation.AddDependentIDs(ids...)
	return _c
}

// AddDependents adds the "dependents" edges to the TaskDependency entity.
func (_c *TaskCreate) AddDependents(v ...*TaskDependency) *TaskCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDependentIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCreate) defaults() {
	if _, ok := _c.mutation.CurrentStage(); !ok {
		v := task.DefaultCurrentStage
		_c.mutation.SetCurrentStage(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := task.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.MaxIterations(); !ok {
		v := task.DefaultMaxIterations
		_c.mutation.SetMaxIterations(v)
	}
	if _, ok := _c.mutation.StageTimeoutSeconds(); !ok {
		v := task.DefaultStageTimeoutSeconds
		_c.mutation.SetStageTimeoutSeconds(v)
	}
	if _, ok := _c.mutation.SilverBullet(); !ok {
		v := task.DefaultSilverBullet
		_c.mutation.SetSilverBullet(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Task.slug"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Task.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cwd(); !ok {
		return &ValidationError{Name: "cwd", err: errors.New(`ent: missing required field "Task.cwd"`)}
	}
	if v, ok := _c.mutation.Cwd(); ok {
		if err := task.CwdValidator(v); err != nil {
			return &ValidationError{Name: "cwd", err: fmt.Errorf(`ent: validator failed for field "Task.cwd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentStage(); !ok {
		return &ValidationError{Name: "current_stage", err: errors.New(`ent: missing required field "Task.current_stage"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Task.priority"`)}
	}
	if _, ok := _c.mutation.MaxIterations(); !ok {
		return &ValidationError{Name: "max_iterations", err: errors.New(`ent: missing required field "Task.max_iterations"`)}
	}
	if _, ok := _c.mutation.StageTimeoutSeconds(); !ok {
		return &ValidationError{Name: "stage_timeout_seconds", err: errors.New(`ent: missing required field "Task.stage_timeout_seconds"`)}
	}
	if _, ok := _c.mutation.SilverBullet(); !ok {
		return &ValidationError{Name: "silver_bullet", err: errors.New(`ent: missing required field "Task.silver_bullet"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Task.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(task.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Cwd(); ok {
		_spec.SetField(task.FieldCwd, field.TypeString, value)
		_node.Cwd = value
	}
	if value, ok := _c.mutation.WorktreePath(); ok {
		_spec.SetField(task.FieldWorktreePath, field.TypeString, value)
		_node.WorktreePath = &value
	}
	if value, ok := _c.mutation.SourceBranch(); ok {
		_spec.SetField(task.FieldSourceBranch, field.TypeString, value)
		_node.SourceBranch = &value
	}
	if value, ok := _c.mutation.TargetBranch(); ok {
		_spec.SetField(task.FieldTargetBranch, field.TypeString, value)
		_node.TargetBranch = &value
	}
	if value, ok := _c.mutation.CurrentStage(); ok {
		_spec.SetField(task.FieldCurrentStage, field.TypeString, value)
		_node.CurrentStage = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(task.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.ParentTaskID(); ok {
		_spec.SetField(task.FieldParentTaskID, field.TypeString, value)
		_node.ParentTaskID = &value
	}
	if value, ok := _c.mutation.MaxIterations(); ok {
		_spec.SetField(task.FieldMaxIterations, field.TypeInt, value)
		_node.MaxIterations = value
	}
	if value, ok := _c.mutation.TokenBudget(); ok {
		_spec.SetField(task.FieldTokenBudget, field.TypeInt, value)
		_node.TokenBudget = &value
	}
	if value, ok := _c.mutation.CostBudgetCents(); ok {
		_spec.SetField(task.FieldCostBudgetCents, field.TypeInt, value)
		_node.CostBudgetCents = &value
	}
	if value, ok := _c.mutation.StageTimeoutSeconds(); ok {
		_spec.SetField(task.FieldStageTimeoutSeconds, field.TypeInt, value)
		_node.StageTimeoutSeconds = value
	}
	if value, ok := _c.mutation.SilverBullet(); ok {
		_spec.SetField(task.FieldSilverBullet, field.TypeBool, value)
		_node.SilverBullet = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(task.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(task.FieldProjectID, field.TypeString, value)
		_node.ProjectID = &value
	}
	if value, ok := _c.mutation.SpawnerID(); ok {
		_spec.SetField(task.FieldSpawnerID, field.TypeString, value)
		_node.SpawnerID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.StageRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.StageRunsTable,
			Columns: []string{task.StageRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stagerun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.PermissionsTable,
			Columns: []string{task.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskpermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DependentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependentsTable,
			Columns: []string{task.DependentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
