// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/task"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskdependency"
)

// TaskDependencyCreate is the builder for creating a TaskDependency entity.
type TaskDependencyCreate struct {
	config
	mutation *TaskDependencyMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *TaskDependencyCreate) SetTaskID(v string) *TaskDependencyCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetDependsOnID sets the "depends_on_id" field.
func (_c *TaskDependencyCreate) SetDependsOnID(v string) *TaskDependencyCreate {
	_c.mutation.SetDependsOnID(v)
	return _c
}

// SetRequiredStage sets the "required_stage" field.
func (_c *TaskDependencyCreate) SetRequiredStage(v string) *TaskDependencyCreate {
	_c.mutation.SetRequiredStage(v)
	return _c
}

// SetNillableRequiredStage sets the "required_stage" field if the given value is not nil.
func (_c *TaskDependencyCreate) SetNillableRequiredStage(v *string) *TaskDependencyCreate {
	if v != nil {
		_c.SetRequiredStage(*v)
	}
	return _c
}

// SetOnCancelAction sets the "on_cancel_action" field.
func (_c *TaskDependencyCreate) SetOnCancelAction(v string) *TaskDependencyCreate {
	_c.mutation.SetOnCancelAction(v)
	return _c
}

// SetNillableOnCancelAction sets the "on_cancel_action" field if the given value is not nil.
func (_c *TaskDependencyCreate) SetNillableOnCancelAction(v *string) *TaskDependencyCreate {
	if v != nil {
		_c.SetOnCancelAction(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskDependencyCreate) SetID(v string) *TaskDependencyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskDependencyCreate) SetTask(v *Task) *TaskDependencyCreate {
	return _c.SetTaskID(v.ID)
}

// SetDependsOn sets the "depends_on" edge to the Task entity.
func (_c *TaskDependencyCreate) SetDependsOn(v *Task) *TaskDependencyCreate {
	return _c.SetDependsOnID(v.ID)
}

// Mutation returns the TaskDependencyMutation object of the builder.
func (_c *TaskDependencyCreate) Mutation() *TaskDependencyMutation {
	return _c.mutation
}

// Save creates the TaskDependency in the database.
func (_c *TaskDependencyCreate) Save(ctx context.Context) (*TaskDependency, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskDependencyCreate) SaveX(ctx context.Context) *TaskDependency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskDependencyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskDependencyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskDependencyCreate) defaults() {
	if _, ok := _c.mutation.RequiredStage(); !ok {
		v := taskdependency.DefaultRequiredStage
		_c.mutation.SetRequiredStage(v)
	}
	if _, ok := _c.mutation.OnCancelAction(); !ok {
		v := taskdependency.DefaultOnCancelAction
		_c.mutation.SetOnCancelAction(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskDependencyCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskDependency.task_id"`)}
	}
	if _, ok := _c.mutation.DependsOnID(); !ok {
		return &ValidationError{Name: "depends_on_id", err: errors.New(`ent: missing required field "TaskDependency.depends_on_id"`)}
	}
	if _, ok := _c.mutation.RequiredStage(); !ok {
		return &ValidationError{Name: "required_stage", err: errors.New(`ent: missing required field "TaskDependency.required_stage"`)}
	}
	if _, ok := _c.mutation.OnCancelAction(); !ok {
		return &ValidationError{Name: "on_cancel_action", err: errors.New(`ent: missing required field "TaskDependency.on_cancel_action"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskDependency.task"`)}
	}
	if len(_c.mutation.DependsOnIDs()) == 0 {
		return &ValidationError{Name: "depends_on", err: errors.New(`ent: missing required edge "TaskDependency.depends_on"`)}
	}
	return nil
}

func (_c *TaskDependencyCreate) sqlSave(ctx context.Context) (*TaskDependency, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TaskDependency.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskDependencyCreate) createSpec() (*TaskDependency, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskDependency{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskdependency.Table, sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RequiredStage(); ok {
		_spec.SetField(taskdependency.FieldRequiredStage, field.TypeString, value)
		_node.RequiredStage = value
	}
	if value, ok := _c.mutation.OnCancelAction(); ok {
		_spec.SetField(taskdependency.FieldOnCancelAction, field.TypeString, value)
		_node.OnCancelAction = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskdependency.TaskTable,
			Columns: []string{taskdependency.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DependsOnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskdependency.DependsOnTable,
			Columns: []string{taskdependency.DependsOnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DependsOnID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskDependencyCreateBulk is the builder for creating many TaskDependency entities in bulk.
type TaskDependencyCreateBulk struct {
	config
	err      error
	builders []*TaskDependencyCreate
}

// Save creates the TaskDependency entities in the database.
func (_c *TaskDependencyCreateBulk) Save(ctx context.Context) ([]*TaskDependency, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskDependency, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskDependencyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskDependencyCreateBulk) SaveX(ctx context.Context) []*TaskDependency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskDependencyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskDependencyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
