// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package sdk provides shared types for the agent-dashboard modules.
*/

/**
 * TokenUsage mirrors the Claude Code session token counters.
 */
export interface TokenUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationTokens: number /* int */;
  cacheReadTokens: number /* int */;
}
/**
 * SessionMeta is read from ~/.claude/usage-data/session-meta/{sessionId}.json
 */
export interface SessionMeta {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  linesAdded: number /* int */;
  linesRemoved: number /* int */;
  filesModified: number /* int */;
  gitCommits: number /* int */;
  toolErrors: number /* int */;
  usesMcp: boolean;
  firstPrompt: string;
}
/**
 * SubAgent represents a sub-agent spawned by a parent Claude session.
 */
export interface SubAgent {
  id: string;
  type: string;
  status: string; // "active" | "completed"
  currentAction: string;
  sessionFile: string;
}
/**
 * TaskInfo is a task tracked by Claude Code's internal task list.
 */
export interface TaskInfo {
  id: string;
  subject: string;
  status: string;
}
/**
 * AgentStatus is the computed activity state of an agent process.
 */
export const AgentStatusActive = "active";
export const AgentStatusWaiting = "waiting";
export const AgentStatusIdle = "idle";
export type AgentStatus = typeof AgentStatusActive | typeof AgentStatusWaiting | typeof AgentStatusIdle;
/**
 * Agent is the unified view of a running Claude Code process.
 */
export interface Agent {
  pid: number /* int */;
  sessionId: string;
  projectPath: string;
  projectName: string;
  cwd: string;
  entrypoint: string; // "cli" | "desktop" | "unknown"
  status: AgentStatus;
  uptime: number /* int64 */; // seconds
  lastActivity: string;
  currentAction: string;
  lastTools: string[];
  tasks: TaskInfo[];
  subagents: SubAgent[];
  tokenUsage: TokenUsage;
  costEstimate: number /* float64 */;
  cacheCreationCostEstimate: number /* float64 */;
  cacheReadCostEstimate: number /* float64 */;
  healthScore: number /* int */;
  model: string;
  codeVersion: string;
  conversationTurns: number /* int */;
  toolCounts: { [key: string]: number /* int */};
  meta?: SessionMeta;
  channelAvailable: boolean;
  lastOutput: string;
  convergenceAlert: boolean;
  convergenceToolName: string;
  errorState: string; // "" | "quota_exhausted" | "rate_limited" | "auth_failed"
  pipelineTaskId?: string;
  pipelineTaskTitle?: string;
  machine?: string;
}
