// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package sdk provides shared types for the agent-dashboard modules.
*/

/**
 * TokenUsage mirrors the Claude Code session token counters.
 */
export interface TokenUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationTokens: number /* int */;
  cacheReadTokens: number /* int */;
}
/**
 * SessionMeta is read from ~/.claude/usage-data/session-meta/{sessionId}.json
 */
export interface SessionMeta {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  linesAdded: number /* int */;
  linesRemoved: number /* int */;
  filesModified: number /* int */;
  gitCommits: number /* int */;
  toolErrors: number /* int */;
  usesMcp: boolean;
  firstPrompt: string;
}
/**
 * SubAgent represents a sub-agent spawned by a parent Claude session.
 */
export interface SubAgent {
  id: string;
  type: string;
  status: string; // "active" | "completed"
  currentAction: string;
  sessionFile: string;
}
/**
 * TaskInfo is a task tracked by Claude Code's internal task list.
 */
export interface TaskInfo {
  id: string;
  subject: string;
  status: string;
}
/**
 * AgentStatus is the computed activity state of an agent process.
 */
export const AgentStatusActive = "active";
export const AgentStatusWaiting = "waiting";
export const AgentStatusIdle = "idle";
export type AgentStatus = typeof AgentStatusActive | typeof AgentStatusWaiting | typeof AgentStatusIdle;
/**
 * Entrypoint describes how the Claude Code process was launched.
 */
export const EntrypointCLI = "cli";
export const EntrypointDesktop = "desktop";
export const EntrypointUnknown = "unknown";
export type Entrypoint = typeof EntrypointCLI | typeof EntrypointDesktop | typeof EntrypointUnknown;
/**
 * Provider identifies which AI coding CLI an agent process belongs to.
 */
export const ProviderClaude = "claude";
export const ProviderCodex = "codex";
export const ProviderGemini = "gemini";
export type Provider = typeof ProviderClaude | typeof ProviderCodex | typeof ProviderGemini;
/**
 * ErrorState describes a recognisable error condition seen in the session log.
 */
export const ErrorStateQuotaExhausted = "quota_exhausted";
export const ErrorStateRateLimited = "rate_limited";
export const ErrorStateAuthFailed = "auth_failed";
export type ErrorState = typeof ErrorStateQuotaExhausted | typeof ErrorStateRateLimited | typeof ErrorStateAuthFailed;
/**
 * SankeyNode is one node in the tool-call Sankey diagram. ID equals Name
 * today but is kept separate so collisions across distinct sources can
 * later be disambiguated.
 */
export interface SankeyNode {
  id: string;
  name: string;
}
/**
 * SankeyLink is one directed source→target flow with an aggregated count.
 */
export interface SankeyLink {
  source: string;
  target: string;
  value: number /* int */;
}
/**
 * SankeyMeta carries summary counters for the Sankey response.
 */
export interface SankeyMeta {
  sessionCount: number /* int */;
  callCount: number /* int */;
}
/**
 * SankeyData is the response payload for GET /api/visualizations/sankey.
 */
export interface SankeyData {
  nodes: SankeyNode[];
  links: SankeyLink[];
  meta: SankeyMeta;
}
/**
 * DAGNode is one node in the session DAG (tool call, assistant turn, or
 * user message). The DAG is per-session so IDs are line-local.
 */
export interface DAGNode {
  id: string;
  type: string; // "tool" | "assistant" | "user"
  label: string;
  ts: string; // RFC3339 timestamp, empty if absent
}
/**
 * DAGLink is one edge in the session DAG. Kind is "chrono" for time-
 * ordered succession or "result" for a tool_use → tool_result match.
 */
export interface DAGLink {
  source: string;
  target: string;
  kind: string;
}
/**
 * DAGData is the response payload for GET /api/visualizations/dag.
 */
export interface DAGData {
  nodes: DAGNode[];
  links: DAGLink[];
}
/**
 * SpawnTreeNode is one session node in the spawn tree. Depth is computed
 * from the root via BFS. ToolCount and CostCents reflect the session,
 * not the cumulative subtree.
 */
export interface SpawnTreeNode {
  id: string;
  label: string;
  depth: number /* int */;
  toolCount: number /* int */;
  costCents: number /* int */;
}
/**
 * SpawnTreeLink is a parent→child spawn relationship.
 */
export interface SpawnTreeLink {
  source: string;
  target: string;
}
/**
 * SpawnTreeData is the response payload for GET /api/visualizations/spawn-tree.
 */
export interface SpawnTreeData {
  roots: string[];
  nodes: SpawnTreeNode[];
  links: SpawnTreeLink[];
}
/**
 * CoOccurrenceMeta carries summary counters for the co-occurrence response.
 */
export interface CoOccurrenceMeta {
  sessionCount: number /* int */;
  truncated: boolean;
}
/**
 * CoOccurrenceData is the response payload for
 * GET /api/visualizations/co-occurrence. Matrix is square with side equal
 * to len(Tools); Matrix[i][j] = sessions containing both Tools[i] and
 * Tools[j] (diagonal = sessions containing the tool at all).
 */
export interface CoOccurrenceData {
  tools: string[];
  matrix: number /* int */[][];
  meta: CoOccurrenceMeta;
}
/**
 * BtwMessage is the last assistant text that appeared alongside tool calls.
 * Message is the text content; Response is reserved for future use.
 */
export interface BtwMessage {
  message: string;
  response?: string;
}
/**
 * WorktreeStatusDTO describes the live git state of a task's worktree.
 * Ahead and Behind are pointers so JSON null is preserved when the base
 * branch cannot be resolved on `origin` (e.g. local-only base).
 */
export interface WorktreeStatusDTO {
  branch: string;
  ahead?: number /* int */;
  behind?: number /* int */;
  dirty: boolean;
  fileCount: number /* int */;
}
/**
 * Agent is the unified view of a running Claude Code process.
 */
export interface Agent {
  pid: number /* int */;
  sessionId: string;
  provider: Provider;
  projectPath: string;
  projectName: string;
  cwd: string;
  entrypoint: Entrypoint;
  status: AgentStatus;
  uptime: number /* int64 */;
  lastActivity: string;
  currentAction?: string;
  lastTools: string[];
  tasks: TaskInfo[];
  subagents: SubAgent[];
  tokenUsage: TokenUsage;
  costEstimate: number /* float64 */;
  cacheCreationCostEstimate: number /* float64 */;
  cacheReadCostEstimate: number /* float64 */;
  healthScore: number /* int */;
  model?: string;
  codeVersion?: string;
  conversationTurns: number /* int */;
  toolCounts: { [key: string]: number /* int */};
  meta?: SessionMeta;
  channelAvailable: boolean;
  lastOutput?: string;
  convergenceAlert: boolean;
  convergenceToolName?: string;
  errorState?: ErrorState;
  pipelineTaskId?: string;
  pipelineTaskTitle?: string;
  machine?: string;
  lastBtw?: BtwMessage;
  /**
   * CostUnknown is true when the provider does not expose token counts and
   * cost cannot be estimated. CostEstimate will be 0 in this case.
   */
  costUnknown?: boolean;
}
